import os
import tempfile
import unittest
import parameterized

from pdf2image import convert_from_path
from Levenshtein import distance

from memoocr.align_ocr import align_ocr

"""
- Test whether state can be saved.
- Test whether saved state can be recovered.
X Test whether PDF can be split into images.
- Test whether image can be OCR'ed.
- Test whether OCR can be cleaned.
"""


class alignOCRTest(unittest.TestCase):
    """Test alignment of original OCR lines with corrected lines."""

    testcases = [
        ('„Hr. E ta tsra a d Helmer, tlieoloZios',
         '„Hr. Etatsraad Helmer, Candidatus theologiæ'),
        ('langt mere oedel og ridderlig Teenkemaade. ^evnne sti',
         'langt mere ædel og ridderlig Tænkemaade. Senere fik'),
        ('Dronning at syre hende og hendes ^Lyn E a rl t il Flandern,',
         'Dronning at føre hende og hendes Søn Earl til Flandern,'),
        ('Vcegten af de Tanker der gennemfarer d e t... hans',
         'Vægten af de Tanker der gennemfarer det. . . hans'),
        ('sine klare j2jne ind i hans.',
         'sine klare Øjne ind i hans.'),
        ('Ord et „passende" -havde i F r u R a n d u ls M u n d',
         'Ordet „passende" havde i Fru Randuls Mund'),
        ('da Afgiften t i l Herremanden heller ikke var uoverkommelig,',
         'da Afgiften til Herremanden heller ikke var uover[- ]kommelig,'),
        ("vceneste Ungmp, nogen kunde se fo r sine Ojne, og",
         "væneste Ungmø, nogen kunde se for sine Øjne, og"),
        ("' D u duer ikke engang til at pudse Solvtoiet ombord i",
         " Du duer ikke engang til at pudse Sølvtøiet ombord i"),
        ("""forsigtig, Pe te r ", vedblev han beroligende, """, """forsigtig, Peter", vedblev han beroligende,"""),
        ("optaget i Baronessens Hjem, dannedes der u v ilkaarligt",
         "optaget i Baronessens Hjem, dannedes der uvil[- ]kaarligt"),
        ("og Vane blevne en S v o b e , hvormed hun hidsede og",
         "og Vane blevne en Svøbe, hvormed hun hidsede og"),
        ("nu rev Mo g e n s en Kniv fra Kaptajnen, ved hvis",
         "nu rev Mogens en Kniv fra Kaptainen, ved hvis"),
        ("nsisomme Liv. T id t og mange Gange har Dristet", "nøisomme Liv. Tidt og mange Gange har Ønsket"),
        ("men med et fluwmrlt, listigt Uddyk i de stygge,",
         "men med et skummelt, listigt Udtryk i de stygge,"),
        ("megen fiin Folelse fra den ene Side og kranket S to lt hed",
         "megen fiin Følelse fra den ene Side og krænket Stolt[- ]hed"),
        ("lo d s Det nagede hende og hver en nok saa ringe", "Det nagede hende og hver en nok saa ringe"),
        ("lille Præsteembede ovre p aa J y lla n d s Hede. Han var",
         "lille Præsteembede ovre paa Jyllands Hede. Han var"),
        ("langt mere oedel og ridderlig Teenkemaade. ^evnne sti",
         "langt mere ædel og ridderlig Tænkemaade. Senere fik"),
        ("koer,. —", "kær. —"),
        ("proegtig F y r. den Thorning! Gid nu Djcevelen", "prægtig Fyr, den Thorning! Gid nu Djævelen"),
        ("indvendte Anker. „D e er jo altid i S e lskab", "indvendte Anker. „De er jo altid i Sel[- ]skab"),
        ("hvis let krusede Vandflade gjengav et tro B illede",
         "hvis let krusede Vandflade gjengav et tro Bil[- ]lede"),
        ("her alene med Alfred. Hun trykkede den -t^odes", "her alene med Alfred. Hun trykkede den Dødes"),
        ("hendes Hensigt at syre Knuds Lig med sig t il L)t.",
         "hendes Hensigt at føre Knuds Lig med sig til St."),
        ("""hende", sagde han med et stjcelmst Smil.""", """hende", sagde han med et skjælmsk Smil."""),
        ("hans Venskab med Gjenbofamilien har sin vcesenlige",
         "hans Venskab med Gjenbofamilien har sin væsen[- ]lige"),
        ("han kastede sine skarpe og funklende L)ine op", "han kastede sine skarpe og funklende Øine op"),
        ("ganske v ift saa klare som m u lig t, det stal Husmoderen",
         "ganske vist saa klare som muligt, det skal Husmo[- ]deren"),
        ("""„T al for eders oenlige Hilsen, unge Herre!" m alede""",
         """„Tak for eders venlige Hilsen, unge Herre!" mæ[- ]lede"""),
        ("falde om mine fljorbnesvangre natlige Vandringer,",
         "falde om mine skjæbnesvangre natlige Vandringer,"),
        ("ere i. Familiens Dagligstue, det ene af de to Vcrrelser,",
         "ere i. Familiens Dagligstue, det ene af de to Væ[- ]relser,"),
        ("idet ban oed S onet af Sidsels luoslige Skikkelse folte",
         "idet han ved Synet af Sidsels hæslige Skikkelse følte"),
        ("disse uforstyrrede Vandringer talte hun saa fo rn u ftig t",
         "disse uforstyrrede Vandringer talte hun saa fornuftigt"),
        ("rastlos op og ned ad G u lv e t... med Armene paa",
         "rastløs op og ned ad Gulvet. . . med Armene paa"),
        ("selv har ikke T alent for Opdragelse, min Ven, D re n gen",
         "selv har ikke Talent for Opdragelse, min Ven, Dren[- ]gen"),
        ('''„M e n hvor kan De kjede Dem, min kjoere N o rstrand?"''',
         '''"„Men hvor kan De kjede Dem, min kjøre Nor[-]strand?"'''),
        ("""„Jeg er Manden, jeg skulde dog ra a d e ............. " —""",
         """„Jeg er Manden, jeg skulde dog raade....." —"""),
        ("„H vo r sorgelige flige Forhold ere, saa ere de dog",
         "„Hvor sørgelige slige Forhold ere, saa ere de dog"),
        ("„D et er et stort Forlangende, og min Kunst rakker",
         "„Det er et stort Forlangende, og min Kunst ræk[- ]ker"),
        ("""„D e t var Dem, Froken E rn a ," fortsatte nu E ta tsraaden, """,
         """„Det var Dem, Frøken Erna, " fortsatte nu Etats[- ]raaden,"""),
        ("„D e t er knap n o k ,.............du kan ikke undvcere",
         "„Det er knap nok, . . . . . du kan ikke undvære"),
        ("„Betrceffende Jer sorrigtunge Beretning, - mcegter",
         "„Betræffende Jer sorrigtunge Beretning, mægter"),
        ("— H p r, F ilip K arm in , alle vi Mcrnd, som", "— Hør, Filip Harmen, alle vi Mænd, som"),
        ("— God K v eld ! raabte d»n Angste muntert", "— God Kveld! raabte den Yngste muntert"),
        ("— D e t gM mig ondt for sorte Filip,", "— Det gjør mig ondt for sorte Filip,"),
        ("saa vidt forgrenede Slcrgt bestandig er traadt i F amilieforbindelser",
         "saa vidt forgrenede Slægt bestandig er traadt i Fa[- ]milieforbindelser"),
        ("vovede det. Agnes stod udelukkende under T a n te n s",
         "vovede det. Agnes stod udelukkende under Tantens"),
        ("uboggelige In d tro k oed sit Gudsfred.", "uhyggelige Indtryk ved sit Gudsfred."),
        ("""thi jeg dandser aldrig med B ja rn e ," svarede hun, """,
         """thi jeg dandser aldrig med Bjørne, " svarede hun,"""),
        ("t i l at udgjpre et helt Livs In d h o ld ? — Stillede Livet",
         "til at udgjøre et helt Livs Indhold? — Stillede Livet"),
        ("t i l M a g t derinde. Den omtalte Pensionist, der tid ligere",
         "til Magt derinde. Den omtalte Pensionist, der tid[- ]ligere"),
        ("svarede P o v l K u re .' D e r seer jeg, han kommer",
         "svarede Povl Kure. Der seer jeg, han kommer"),
        ("sorlamget ved, at Knuds trofaste Venner ^vend undsen",
         "forlænget ved, at Knuds trofaste Venner Svend Trund[- ]sen"),
        ("solgte da en Del af sine Ejendomme og drog t il Sesteren",
         "solgte da en Del af sine Ejendomme og drog til Søste[- ]ren"),
        ("skimtede Fare for Opnaaelsen af sine Onsker og Fo rhaabninger",
         "skimtede Fare for Opnaaelsen af sine Ønsker og For[- ]haabninger"),
        ("sin unge Hustru og den lille Son, hvormed deres dEgteskab",
         "sin unge Hustru og den lille Søn, hvormed deres Ægte[- ]skab"),
        ("sige t il sin Broderspn og Y n d lin g : „See!", "sige til sin Brodersøn og Yndling: „See!"),
        ("ved hans O rd . „ J a , P e t e r , jeg er forsigtig, og for",
         "ved hans Ord. „Ja, Peter, jeg er forsigtig, og for"),
        ("den rodstoeggede Djcevel neppe havde ventet. Holk",
         "den rødskæggede Djævel neppe havde ventet. Holk"),
        ("„som jeg sogte, for at udbede mig en D a n d s", "„som jeg søgte, for at udbede mig en Dands"),
        ("ankommet. Begge Skibe seilede ufortovet til Kjobenhavn,",
         "ankommet. Begge Skibe seilede ufortøvet til Kjø[- ]benhavn,"),
        ("S tra a le r ikke kunne troenge derigjennem. N a a r man",
         "Straaler ikke kunne trænge derigjennem. Naar man"),
        ("S ted er danne et saa toet Lovtag over Aaen, at S o le n s",
         "Steder danne et saa tæt Løvtag over Aaen, at Solens"),
        ("R e g t og Pleje, den var hverken haard eller uretscerdig,",
         "Røgt og Pleje, den var hverken haard eller uretfærdig,"),
        ("E t Forsog paa at indrette et S o lu h r i Vindueskarmen",
         "Et Forsøg paa at indrette et Soluhr i Vindues[- ]karmen"),
        ("R an d u l vare disse Egenstaber ved N a tu r , Opdragelse",
         "Randul vare disse Egenskaber ved Natur, Opdragelse"),
        (
        '''P eter. D u har vel h o rt T ale om Jo rg e n L ind?"''', '''Peter.Du har vel hørt Tale om Jørgen Lind?"'''),
        ("""Ord et „passende" - havde i F r u R a n d u ls M u n d""", """Ordet „passende" havde i Fru Randuls Mund"""),
        ("S trom m en mellem disse Troeer, der staae som en",
         "Strømmen mellem disse Træer, der staae som en"),
        ("Efter e, Diebliks Forlob reiste han sig, omfavnede",
         "Efter et Øiebliks Forløb reiste han sig, omfavnede"),
        ("beskedent og a lv o rlig t, at det kunde vcere Model for",
         "beskedent og alvorligt, at det kunde være Model for"),
        ("Marmortropper, steg de to Mcend ned i en Vevcertuingskjcelder,",
         "Marmortrapper, steg de to Mænd ned i en Bevært[- ]ningskjælder,"),
        ("En af de stcerkesle M a n d greb mig og smed mig op paa",
         "En af de stærkesle Mænd greb mig og smed mig op paa"),
        ("Man kan ikke tage fejl af d e t... det er en T a n k e ...",
         "Man kan ikke tage fejl af det. . . det er en Tanke. . ."),
        ("Kommando. Han kom endnu med al den t ilbageholdne",
         "Kommando. Han kom endnu med al den til[- ]bageholdne"),
        ("Et Oieblik ester traadte. Robert ind med sin lille",
         "Et Øieblik efter traadte Robert ind med sin lille"),
        ("Kattegattet. S k jo n n e, med Lyng og Skov bevoxede",
         "Kattegattet. Skjønne, med Lyng og Skov bevoxede"),
        ("""Men, P e te r ", tilfoiede han, og her antog hans Ansigt""",
         """Men, Peter", tilføiede han, og her antog hans Ansigt"""),
        ("Dermed gik han, fulgt af den G am les Velsignelser,",
         "Dermed gik han, fulgt af den Gamles Velsig[- ]nelser,"),
        ("Stivhed et aarelangt Ophold mellem Orkener", "Stivhed et aarelangt Ophold mellem Ør[- ]kener"),
        ("Ig e n en S cen efo ran d rin g ... fra London til Konstantinopel.",
         "Igen en Sceneforandring. . . fra London til Kon[- ]stantinopel."),
        (":! noermede sig Holdepunktet.", "nærmede sig Høidepunktet."),
        ('''aldrig vceret k ja rlig t."''', '''aldrig været kjærligt."'''),
        ("""^ cerekjcer G u t forsvarer sine Venner med sit Hjerteblod", """,
         """ærekjær Gut forsvarer sine Venner med sit Hjerteblod","""),
        ("Voer et en oerlig M and.", "været en ærlig Mand."),
        ("A trin g e r, om at denne var en gammel Dame,", "Ytringer, om at denne var en gammel Dame,"),
        ("Stormanden, „kan ride frem. V i have Wrinde i", "Stormanden, „kan ride frem. Vi have Ærinde i"),
        ("Anseelse, og hvis Navn Du kun bor. ncevne med", "Anseelse, og hvis Navn Du kun bør nævne med"),
        ("Trcevcerk, eller i den langtrukne Piben, der", "Træværk, eller i den langtrukne Piben, der"),
        ("Trcek og et stort msrkebrunt Ska'g — kort sagt de",
         "Træk og et stort møkebrunt Skæg — kort sagt de"),
        ("Tone,. „Voer derfor taus, taus som den", "Tone, „Vær derfor taus, taus som den"),
        ("B a r n , som F ru R a n d u l i sine Tanker altid kaldte",
         "Barn, som Fru Randul i sine Tanker altid kaldte"),
        ("T o Mcend ncermede sig til B ordet. Den", "To Mænd nærmede sig til Bordet. Den"),
        ("B red d er, paa Herresædets Enemoerker, ere toet bevorede",
         "Bredder, paa Herresædets Enemærker, ere tæt be[- ]voxede"),
        ("Synner, der hiin skjcebnesvangre Nide J u li havde",
         "Sønner, der hiin skjæbnesvangre 10de Juli havde"),
        ("^ mindste uden at sige Farvel, var mig umuligt.", "uden at sige Farvel, var mig umuligt."),
        ("(ttaarde, nej. H r. Ridder, jeg stal oel gjore eder Pinen",
         "Gaarde, nej, Hr. Ridder, jeg skal vel gjøre eder Pinen"),
        (
            "„S n a v s , H r. Doctor! Det T o i trcrkker mig i", "„Snavs , Hr. Doctor! Det Tøi trækker mig i"),
        ("Hun stirrede ud gennem G lasruderne i P ortechaisen,",
         "Hun stirrede ud gennem Glasruderne i Porte[- ]chaisen,"),
        ("var aldeles urykkelig vg mindedes tillig e , ved B a ro n essens",
         "var aldeles urykkelig og mindedes tillige, ved Baron[- ]essens"),
        ("En Tjener traadte ind og sagde, at der var en A rbeider,",
         "En Tjener traadte ind og sagde, at der var en Ar[- ]beider,"),
        ("Agnes; men der blev svrget for hendes Fo rn ø d en heder,",
         "Agnes; men der blev sørget for hendes Fornøden[- ]heder,"),
        ("Med spamdt Opmwrksomled lyttede den lille F a milie",
         "Med spændt Opmærksomhed lyttede den lille Fa[- ]milie"),
        ("Im id le rtid var Hasting dog ingenlunde as de I v rige",
         "Imidlertid var Hasting dog ingenlunde af de Iv[- ]rige"),
        ("det Kunststykke med og gav ham en udforlig F rem stilling",
         "det Kunststykke med og gav ham en udførlig Frem[- ]stilling"),
        ("af Eder, og en slig dristig Tanke er ret pikant, i S æ r deleshed",
         "af Eder, og en slig dristig Tanke er ret pikant, i Sær[- ]deleshed"),
        ("""for O je kaldte F r u R a n d u l det „ P l i g t ", tidlig at""",
         """ for Øje kaldte Fru Randul det „Pligt", tidlig at"""),
        ("ham ind, at denne kunde vcere i Besiddelse af. O p dagelsen",
         "ham ind, at denne kunde være i Besiddelse af. Op[- ]dagelsen"),
        ("han Svaret. Det kom ikke strax, ej heller var S am tykket",
         "han Svaret. Det kom ikke strax, ej heller var Sam[- ]tykket"),
        ("Vi kunne ikke frakjende de tyske Kvinder en D y g tighed",
         "Vi kunne ikke frakjende de tyske Kvinder en Dyg[- ]tighed"),
        ("T ry lle r i for ham, han holdt af at se disse mprke alvorlige",
         "Trylleri for ham, han holdt af at se disse mørke al[- ]vorlige"),
        (
            "! Jeg vilde bort medens det endnu var T id ; men", "Jeg vilde bort medens det endnu var Tid; men"),
        ('''men sank kraftlos tilbage. „Nei, De maa vurc taalmodig!"''',
         '''men sank kraftløs tilbage.„Nei, De maa være taal[-]modig!"'''),
        ("og stenede 8)serge og fortvivlede Fnnglestraekninger",
         "og stenede Bjerge og fortvivlede Junglestræk[- ]ninger"),
        ("""s "S to p lid t" raabte nu Mo g e n s ,""", """„Stop lidt" raabte nu Mogens, """),
        ("s og uden videre greb han mig i Brystet og Let ene", "og uden videre greb han mig i Brystet og det ene"),
        ("sig ned, hoeldte han nogle Draaber af Flaskens I n d hold",
         "sig ned, hældte han nogle Draaber af Flaskens Ind[- ]hold"),
        ("Brandt — i „Hvad ser jeg, — Djcevlens Skind og", "„Hvad ser jeg, — Brandt — i Djævlens Skind og"),
        ("I d a Krabbe som ZEgtefolk. — D a IGrubbe strax efter",
         "Ida Krabbe som Ægtefolk. — Da Grubbe strax efter"),
        ("Det er ogsaa kun et F o rso g ... thi hans Ojne har",
         "Det er ogsaa kun et Forsøg. . . thi hans Øjne har"),
        ("S o v i g g a a r d * ) har en overmaade deilig B e liggenhed",
         "Søviggaard *) har en overmaade deilig Be[- ]liggenhed"),
        ("„Hr. E ta tsra a d Helmer, tlieoloZios", "„Hr. Etatsraad Helmer, Candidatus theologiæ"),
        ("Der forlober M in u tte r... K v a rte re r... og bestandig",
         "Der forløber Minutter. . . Kvarterer. . . og be[- ]standig"),
        ("""j „Seierskrandsen", tilfoiede han leende, """, """„Seierskrandsen", tilføiede han leende."""),
        ("iagttage Kvindernes travle Fcrrd. Hans Udre", "at iagttage Kvindernes travle Færd. Hans Ydre"),
        ("' D u duer ikke engang til at pudse Solvtoiet ombord i",
         " Du duer ikke engang til at pudse Sølvtøiet ombord i")
    ]

    testcases2 = [("! Jeg vilde bort medens det endnu var T id ; men", "Jeg vilde bort medens det endnu var Tid; men"),
("hvilken Stilling han havde tilbragt fire Aar, og forst", "hvilken Stilling han havde tilbragt fire Aar, og først"),
("hvorledes har Du faget Kundskab om, hvad der er", "hvorledes har Du faaet Kundskab om, hvad der er"),
("i Fcerd med at desertere. Hans Dom var snart", "i Færd med at desertere. Hans Dom var snart"),
("i Hovedstaden; men jeg fial nok samle en heel Armee", "i Hovedstaden; men jeg skal nok samle en heel Armee"),
("i Morgen skulde faa Lejlighed t il personlig at takke", "i Morgen skulde faa Lejlighed til personlig at takke"),
("i den sydostlige D el af Vendsyssel, ved", "i den sydostlige Del af Vendsyssel, ved"),
("hun modtog, naar hun kom fra eller gik t i l Marken,", "hun modtog, naar hun kom fra eller gik til Marken,"),
("i deres egne Stater og indtage en hcederlig", "i deres egne Stater og indtage en hæderlig"),
("idet ban oed S onet af Sidsels luoslige Skikkelse folte", "idet han ved Synet af Sidsels hæslige Skikkelse følte"),
("idet han maa have fo lt Medlidenhed med mig ved", "idet han maa have følt Medlidenhed med mig ved"),
("igjen at forlade den; thi han havde sogt og faaet et", "igjen at forlade den; thi han havde søgt og faaet et"),
("ikke Livet igjennem sidde under en Osteklokke! D u", "ikke Livet igjennem sidde under en Osteklokke! Du"),
("ikke den uafviselige Fordring, at enhver skulde syge at", "ikke den uafviselige Fordring, at enhver skulde søge at"),
("ikke passer eller er sodt og", "ikke passer eller er født og"),
("i en krumboiet Stilling stirrende ned i de halvtslukte", "i en krumbøiet Stilling stirrende ned i de halvt[- ]slukte"),
("ikke, at den ene af de to hvervede unge Mcend var", "ikke, at den ene af de to hvervede unge Mænd var"),
("hun havde havt Beundrere og Elskere i Dnsinviis, at hun", "hun havde havt Beundrere og Elskere i Dusinviis, at hun"),
("hjcelpe Dig, paa anden Maade formaaer jeg ikke at staa", "hjælpe Dig, paa anden Maade formaaer jeg ikke at staa"),
("har hans Anbefaling, stal jeg reise et Laan, det v il vcere", "har hans Anbefaling, skal jeg reise et Laan, det vil være"),
("har hun ikke seet hverken Slcegt eller Venner; derfor", "har hun ikke seet hverken Slægt eller Venner; der[- ]for"),
("har jeg ofte hort Dem omtale som en begavet og", "har jeg ofte hørt Dem omtale som en begavet og"),
("havde gjort Alt for at troekke dem til sig, men havde", "havde gjort Alt for at trække dem til sig, men havde"),
("havde hendes Mildhed bojet Ynglingens trodsige", "havde hendes Mildhed bøjet Ynglingens trod[- ]sige"),
("havde iinidlertid opsat sin Afrejse, fordi det var", "havde imidlertid opsat sin Afrejse, fordi det var"),
("hun et forstende Blik paa Henrik og steeg op ad", "hun et forskende Blik paa Henrik og steeg op ad"),
("hendes Vine slukkedes.", "hendes Øine slukkedes."),
("hendes og hendes Husbonds Onsker. Denne Forlegenhed", "hendes og hendes Husbonds Ønsker. Denne For[- ]legenhed"),
("hente Liget, da udbredte sig overalt i S t. Albani Kirke", "hente Liget, da udbredte sig overalt i St. Albani Kirke"),
("her da! M en han maa have det anderledes. N a a r", "her da! Men han maa have det anderledes. Naar"),
("her, og var flink og arbeidsom. — Da dode Barnet;", "her, og var flink og arbeidsom. — Da døde Barnet;"),
("heraf sremavlede imidlertid Tanker hos ham, der", "heraf fremavlede imidlertid Tanker hos ham, der"),
("hendes Hensigt at syre Knuds Lig med sig t il L)t.", "hendes Hensigt at føre Knuds Lig med sig til St."),
("imidlertid ufravendt og gjennemtrcengende.", "imidlertid ufravendt og gjennemtrængende."),
("imod sig, naar kun han fandt ham i Besiddelse-af", "imod sig, naar kun han fandt ham i Besiddelse af"),
("man en smuk Sommerdag pludselig kan se Hunlen", "man en smuk Sommerdag pludselig kan se Himlen"),
("mange vare de varme Blikke og hjcertelige Hilsener,", "mange vare de varme Blikke og hjærtelige Hilsener,"),
("matte graae Dine glindsede af en uhyggelig Ild.", "matte graae Øine glindsede af en uhyggelig Ild."),
("med den Dode.", "med den Døde."),
("med det vaade Haar kcrmmet glat ned i Panden,", "med det vaade Haar kæmmet glat ned i Pan[- ]den,"),
("med disse Sententser var hun bleven opfsdt og optugtet,", "med disse Sententser var hun bleven opfødt og op[- ]tugtet,"),
("maa vi ikke vente Hjalp. Politiet har nok at bestille", "maa vi ikke vente Hjælp. Politiet har nok at bestille"),
("med et Suk i han kan, hvor", "med et Suk; han kan, hvor"),
("megen fiin Folelse fra den ene Side og kranket S to lt hed", "megen fiin Følelse fra den ene Side og krænket Stolt[- ]hed"),
("men altid forgjceves, at besejre den, og ingen anden", "men altid forgjæves, at besejre den, og ingen anden"),
("men at kun hans Onkels Onske havde bestemt ham", "men at kun hans Onkels Ønske havde bestemt ham"),
("men hvor man fik Planten fra med de slemme Rsdder,", "men hvor man fik Planten fra med de slemme Rødder,"),
("men med et fluwmrlt, listigt Uddyk i de stygge,", "men med et skummelt, listigt Udtryk i de stygge,"),
("med et balvt spørgende, halvt vredt Blik. I", "med et halvt spørgende, halvt vredt Blik. I"),
("maa noies med et beskedent In d b lik . Ruderne ere", "maa nøies med et beskedent Indblik. Ruderne ere"),
("lune Passiar og deres Kortspil ved et Nodstud at", "lune Passiar og deres Kortspil ved et Nødskud at"),
("lod sig ikke afhente as Baronessens Tjener, for at han", "lod sig ikke afhente af Baronessens Tjener, for at han"),
("indvendte Anker. „D e er jo altid i S e lskab", "indvendte Anker. „De er jo altid i Sel[- ]skab"),
("ingen Steder. I alle de Aar, I have vceret gifte,", "ingen Steder. I alle de Aar, I have været gifte,"),
("jagede alle sine omgivende. „W ir sind zur Arbeit", "jagede alle sine omgivende. „Wir sind zur Arbeit"),
("jeg seer Dig kun hver Sondag, men jeg", "jeg seer Dig kun hver Søndag, men jeg"),
("kan, svarede Greven. Gjor imidlertid din Pligt, se at", "kan, svarede Greven. Gjør imidlertid din Pligt, se at"),
("kimse paa Nasen ad en gammel Kavaler som mig,", "kimse paa Næsen ad en gammel Kavaler som mig,"),
("kun syttenaarige I d a Krabbe.", "kun syttenaarige Ida Krabbe."),
("l", "11"),
("lang og tvecrgget Matroskniv foran sig i Barken", "lang og tveægget Matroskniv foran sig i Barken"),
("levede de et tilfreds og stille L iv med hinanden.", "levede de et tilfreds og stille Liv med hin[- ]anden."),
("lige saa lidt som vi ponse paa at yppe Kiv med", "lige saa lidt som vi pønse paa at yppe Kiv med"),
("ligger fjcernt fra hans Forretning og alle de Interesser,", "ligger fjærnt fra hans Forretning og alle de Interesser,"),
("lille Præsteembede ovre p aa J y lla n d s Hede. Han var", "lille Præsteembede ovre paa Jyllands Hede. Han var"),
("lille, men hyggelig Lejlighed. Antag et andet Navn,", "lille, men hyggelig Leilighed. Antag et andet Navn,"),
("hans Lceber sig til et underligt Smil der indeholdt", "hans Læber sig til et underligt Smil der indeholdt"),
("han; „denne Tantes evindelige Pjatten om, at D u", "han; „denne Tantes evindelige Pjatten om, at Du"),
("han, der meget vanskelig kunde afslaa en Begcering,", "han, der meget vanskelig kunde afslaa en Begæring,"),
("han kommer hjem fra S k olen, skal han ikke drive", "han kommer hjem fra Skolen, skal han ikke drive"),
("derfor ogsaa lykkedes mig ikke at gjore nogen Ulykke.", "derfor ogsaa lykkedes mig ikke at gjøre nogen Ulykke."),
("derom tik Madam Melong?", "derom til Madam Melong?"),
("derpaa reiste den Forstkomne sig og begyndte", "derpaa reiste den Førstkomne sig og be[- ]gyndte"),
("det efter Retfærdighed, saa skulde D u ingen have,", "det efter Retfærdighed, saa skulde Du ingen have,"),
("det er: hvordan kan det vcere, at Eders nu allerede", "det er: hvordan kan det være, at Eders nu allerede"),
("det samme milde S m il, der ogsaa havde hilst hendes", "det samme milde Smil, der ogsaa havde hilst hendes"),
("der pnskede at tale med Professoren.", "der ønskede at tale med Professoren."),
("det var ham muligt at opfylde, dog lovet at gpre", "det var ham muligt at opfylde, dog lovet at gøre"),
("eder. Tugt mig kun for mine Ord, oar det end med", "eder. Tugt mig kun for mine Ord, var det end med"),
("egentlig for? Hvad udrettede hun? Hun lcengtes", "egentlig for? Hvad udrettede hun? Hun længtes"),
("egentlige Sammenhceng maatte han atter sortcelle,", "egentlige Sammenhæng maatte han atter fortælle,"),
("en Konges Ord kun formaaer saare lidet, iscer hvis", "en Konges Ord kun formaaer saare lidet, især hvis"),
("disse Dage ham lyse og milde som ingen for i hans", "disse Dage ham lyse og milde som ingen før i hans"),
("der i dette Djeblik dannede Hovedgruppen.", "der i dette Øjeblik dannede Hovedgruppen."),
("den. Lad hende imidlertid bare komme ud i Kjokkenct,", "den. Lad hende imidlertid bare komme ud i Kjøkkenet,"),
("den stjonne Morgana i tre Hundred Aar; men nu", "den skjønne Morgana i tre Hundred Aar; men nu"),
("da Afgiften t i l Herremanden heller ikke var uoverkommelig,", "da Afgiften til Herremanden heller ikke var uover[- ]kommelig,"),
("da Holger let kunde tjene dem t il den Tid.", "da Holger let kunde tjene dem til den Tid."),
("da formaaer jeg ikke at redde D ig , og selv om det,", "da formaaer jeg ikke at redde Dig , og selv om det,"),
("de deilige Hcender ikke ogsaa at prydes paa det", "de deilige Hænder ikke ogsaa at prydes paa det"),
("de plagede ham ikke med mange Sporgsmaal, men", "de plagede ham ikke med mange Spørgsmaal, men"),
("dem godt derfor; og send Bud til Politiet og sog", "dem godt derfor; og send Bud til Politiet og søg"),
("dem. En ung Herre, ifo rt en graa Sommerdragt,", "dem. En ung Herre, iført en graa Sommerdragt,"),
("dem. Han var sin Bys rigeste og mest ansete Mand.", "dem. Han var sin Bys rigeste og mest ansete Mand,"),
("den Niende. Otto Ludvig var en hoi, smuk Mand", "den Niende. Otto Ludvig var en høi, smuk Mand"),
("den Opfattelse, at hun var en fattig P ig e , som i", "den Opfattelse, at hun var en fattig Pige, som i"),
("den ene af de to Mcend en hoverende Latter, der", "den ene af de to Mænd en hoverende Latter, der"),
("den plumpe Ligesremhed, der var god Tone i de Kredse,", "den plumpe Ligefremhed, der var god Tone i de Kredse,"),
("den rodstoeggede Djcevel neppe havde ventet. Holk", "den rødskæggede Djævel neppe havde ventet. Holk"),
("en Kurv med sire saa nydelige fede Kyllinger, som", "en Kurv med fire saa nydelige fede Kyllinger, som"),
("mere liv lig uden at forstyrre det gode", "mere livlig uden at forstyrre det gode"),
("en Svaghed, som det aldrig et Oieblik var faldet", "en Svaghed, som det aldrig et Øieblik var faldet"),
("en alvorlig og meget intelligent Mand. D r .", "en alvorlig og meget intelligent Mand. Dr."),
("frem gjennem de hoie Bregner, til han kom ind", "frem gjennem de høie Bregner, til han kom ind"),
("frygtede hun for at hore saadanne Ord af hans", "frygtede hun for at høre saadanne Ord af hans"),
("gaar Herren rastlos frem og tilbage i Kontoret.", "gaar Herren rastløs frem og tilbage i Kontoret."),
("gamle Ven! stsnnede den Ulykkelige.", "gamle Ven! stønnede den Ulykkelige."),
("ganske v ift saa klare som m u lig t, det stal Husmoderen", "ganske vist saa klare som muligt, det skal Husmo[- ]deren"),
("fra nu af bekymrede hun sig om In te t, drev om og", "fra nu af bekymrede hun sig om Intet, drev om og"),
("ham med Moie at komme op i Toppen af dette.", "ham med Møie at komme op i Toppen af dette."),
("ham saaledes, at han fik In te t sagt.", "ham saaledes, at han fik Intet sagt."),
("han gav Betlersken en Almisse. „Voer saa god,", "han gav Betlersken en Almisse. „Vær saa god,"),
("han greb hendes Haand og kyssede den; „niaa jeg", "han greb hendes Haand og kyssede den; „maa jeg"),
("han han igjen kom t il sig selv; men han var alene", "han han igjen kom til sig selv; men han var alene"),
("han ikke pleiet! Ingen Moder og Soster kunde have", "han ikke pleiet! Ingen Moder og Søster kunde have"),
("ham ind, at denne kunde vcere i Besiddelse af. O p dagelsen", "ham ind, at denne kunde være i Besiddelse af. Op[- ]dagelsen"),
("fra det Sted, hvorpaa han befinder s ig ... den", "fra det Sted, hvorpaa han befinder sig. . . den"),
("fra den anden. Nu ja, S lig t har ofte gjort Veien", "fra den anden. Nu ja, Sligt har ofte gjort Veien"),
("fra P apiret og dets Indhold.", "fra Papiret og dets Indhold."),
("en eneste Tanke, der beskæftiger h am ... der optager", "en eneste Tanke, der beskæftiger ham. . . der optager"),
("en hel Vinter, eller rettere, vceret fortryllet, ligesom", "en hel Vinter, eller rettere, været fortryllet, ligesom"),
("en uomstødelig M a g t. Hendes M a n d havde forsegt,", "en uomstødelig Magt. Hendes Mand havde forsøgt,"),
("er anmassende at fordomme dem. Det", "er anmassende at fordømme dem. Det"),
("et himmelsk Lys ; hun blev slagen as Forbauselse, afstod", "et himmelsk Lys; hun blev slagen af Forbauselse, afstod"),
("fcerdig, som jeg imorgen viser en Professor; naar jeg", "færdig, som jeg imorgen viser en Professor; naar jeg"),
("fial jeg se at hverve Folk, som kunne forsvare", "skal jeg se at hverve Folk, som kunne forsvare"),
("fik et S la g i Ansigtet, som kastede ham til Jorden.", "fik et Slag i Ansigtet, som kastede ham til Jorden."),
("filede paa et lille Hjul, der var befcestet i en Miniaturudgave", "filede paa et lille Hjul, der var befæstet i en Miniatur[- ]udgave"),
("for at ombede Dankongen naadigen skjcenke sit", "for at ombede Dankongen naadigen skjænke sit"),
("for at redde Eder. Tag til Paris, opsog Eder en", "for at redde Eder. Tag til Paris, opsøg Eder en"),
("for, at det var en Gentleman, som burde hore", "for, at det var en Gentleman, som burde høre"),
("forklcedte Nanna med bankende Hjerte sneg sig forbi", "forklædte Nanna med bankende Hjerte sneg sig forbi"),
("forstyrret Eders Maaltid; men nu iler jeg hjem fv r", "forstyrret Eders Maaltid; men nu iler jeg hjem for"),
("en Vild Krattet og stod sig som en Slange", "en Vild Krattet og skød sig som en Slange"),
("mig se: jeg gik i mit femtende A ar, at de puttede", "mig se: jeg gik i mit femtende Aar, at de puttede"),
("mig, Herr Musset, jeg feiler In tet, jeg har det jo", "mig, Herr Musset, jeg feiler Intet, jeg har det jo"),
("— God K v eld ! raabte d»n Angste muntert", "— God Kveld! raabte den Yngste muntert"),
("— H p r, F ilip K arm in , alle vi Mcrnd, som", "— Hør, Filip Harmen, alle vi Mænd, som"),
("— Hvad pnfler Dc?", "— Hvad ønker De?"),
("— Ja, med Guds Hjcelp.", "— Ja, med Guds Hjælp."),
("— Jeg stal frelse Dig, sagde Robert.", "— Jeg skal frelse Dig, sagde Robert."),
("— Missorstaa mig ikke, Janne: Jeg v il hjcelpe", "— Misforstaa mig ikke, Janne: Jeg vil hjælpe"),
("— Det behover Du strengt taget heller ikke;", "— Det behøver Du strengt taget heller ikke;"),
("— Nei, tro ikke S lig t!", "— Nei, tro ikke Sligt!"),
("— Tak Os ikke for det viser sig, at Du har", "— Tak Os ikke før det viser sig, at Du har"),
("„ I er en forfaren og klog Koinde, der kan raade", "„I er en forfaren og klog Kvinde, der kan raade"),
("„Betrceffende Jer sorrigtunge Beretning, - mcegter", "„Betræffende Jer sorrigtunge Beretning, mægter"),
("— O, Tak; Du v il?", "— O, Tak; Du vil?"),
("— Ak, jeg har allerede leenge anet, at det vilde", "— Ak, jeg har allerede længe anet, at det vilde"),
("»Jo, jeg agter at medtage min dyrebare Faders", "„Jo, jeg agter at medtage min dyrebare Faders"),
("voxede end mere, da Magnus fcestede sit", "voxede end mere, da Magnus fæstede sit"),
("t i l M a g t derinde. Den omtalte Pensionist, der tid ligere", "til Magt derinde. Den omtalte Pensionist, der tid[- ]ligere"),
("t il Hedeby, mens Svend og", "til Hedeby, mens Svend og"),
("thi denne var i Grossererens Dine en temmelig ubetydelig", "thi denne var i Grossererens Øine en temmelig ube[- ]tydelig"),
("tog hun igjen P la d s paa T rappen.", "tog hun igjen Plads paa Trappen."),
("udprcegede og ret smukke, om end noget storslaaede", "udprægede og ret smukke, om end noget storslaaede"),
("uhyggelig Drym.", "uhyggelig Drøm."),
("under Trccet, hvor Flygtningen havde skjult sig.", "under Træet, hvor Flygtningen havde skjult sig."),
("vaklende Udtryk i Vinene og om Munden,", "vaklende Udtryk i Øinene og om Munden,"),
("var tilstrækkelig styg t il helt at kunne ignoreres, men", "var tilstrækkelig styg til helt at kunne ignoreres, men"),
("var, og vilde ikke have lagt nogen Voegt derpaa, havde", "var, og vilde ikke have lagt nogen Vægt derpaa, havde"),
("vare brave B ornholm ere, der ikke vilde have", "vare brave Bornholmere, der ikke vilde have"),
("ved at fceste en stor Naal midt i en Kreds", "ved at fæste en stor Naal midt i en Kreds"),
("vil nok kraftig understotte Forsvaret. Kniber det for", "vil nok kraftig understøtte Forsvaret. Kniber det for"),
("vilde have valgt den S tillin g , hvori han befandt sig,", "vilde have valgt den Stilling, hvori han befandt sig,"),
("vist ingen Fortroed. — Lad os saa komme afsted.", "vist ingen Fortræd. — Lad os saa komme afsted."),
("svarede P o v l K u re .' D e r seer jeg, han kommer", "svarede Povl Kure. Der seer jeg, han kommer"),
("„D e r var en Gang, — ja saaledes plejer jo enhver", "„Der var en Gang, — ja saaledes plejer jo en[- ]hver"),
("„D et er et stort Forlangende, og min Kunst rakker", "„Det er et stort Forlangende, og min Kunst ræk[- ]ker"),
("„Jeg var ikke stort mer end en D reng, ja lad", "„Jeg var ikke stort mer end en Dreng, ja lad"),
("„Jeg vil ikke gjore mig klogere end jeg er,", "„Jeg vil ikke gjøre mig klogere end jeg er,"),
("„M e n som jeg ingen P ris scetter paa at erhverve", "„Men som jeg ingen Pris sætter paa at erhverve"),
("„Maaske dog, naar jeg siger dem, at min Fatter,", "„Maaske dog, naar jeg siger dem, at min Fætter,"),
("„N a a , Norstrand! hvorledes gaaer det saa med", "„Naa, Norstrand! hvorledes gaaer det saa med"),
("„Jeg tanker, at den er snart fan-dig; men gik", "„Jeg tænker, at den er snart færdig; men gik"),
("„S n a v s , H r. Doctor! Det T o i trcrkker mig i", "„Snavs , Hr. Doctor! Det Tøi trækker mig i"),
("„V e l var hun Ridderdotter, stod dog ene og levede", "„Vel var hun Ridderdotter, stod dog ene og le[- ]vede"),
("„Jeg for min Part takker imidlertid styldigst,", "„Jeg for min Part takker imidlertid skyldigst,"),
("„Ikke for den, som fpler sig tilfredsstillet derved,", "„Ikke for den, som føler sig tilfredsstillet derved,"),
("„D et var ogsaa noget at byde Folk, — otte", "„Det var ogsaa noget at byde Folk, — otte"),
("„Det er fuldkommen sandt, men er der Ingen as", "„Det er fuldkommen sandt, men er der Ingen af"),
("„Det har jeg, A lfre d ! Jeg soner den Synd, der", "„Det har jeg, Alfred! Jeg soner den Synd, der"),
("„E n fager Jom fru bar oendt eders Hsirrte til", "„En fager Jomfru har vendt eders Hjærte til"),
("„En Datter af Renteskriver Rosenborg og Kammerpigen,", "„En Datter af Renteskriver Rosenberg og Kammer[- ]pigen,"),
("„Er I ikke rced for at ride saa ene? En fornem", "„Er I ikke ræd for at ride saa ene? En for[- ]nem"),
("„Forleden Nat dromte jeg, at Sverig lurede", "„Forleden Nat drømte jeg, at Sverig lurede"),
("„Frygter I , saa reiser jeg uden Eders Hjoelp.", "„Frygter I, saa reiser jeg uden Eders Hjælp."),
("„Her i Landet moder man kun den regjerende", "„Her i Landet møder man kun den regjerende"),
("„Hvorfor ikke det? Ligesaa godt nu som t il", "„Hvorfor ikke det? Ligesaa godt nu som til"),
("„D e t har", "„Det har"),
("blive kaldt ud paa det oprorte Hav.", "blive kaldt ud paa det oprørte Hav."),
("svarede Offe med Selvfolelse, og han syntes at voxe,", "svarede Offe med Selvfølelse, og han syntes at voxe,"),
("streg Flere.", "skreg Flere."),
("og min Historielcerer, kort sagt alle mine andre", "og min Historielærer, kort sagt alle mine andre"),
("og rolig Sovn.", "og rolig Søvn."),
("og, da hun var gjennemtrcengt af Selvgodhed", "og, da hun var gjennemtrængt af Selvgodhed"),
("ogsaa dette dsd hen, uden at kunne tilfredsstilles.", "ogsaa dette død hen, uden at kunne tilfredsstilles."),
("om Livet, hvori der hang et langt Svcrrd med blankpoleret", "om Livet, hvori der hang et langt Sværd med blank[- ]poleret"),
("om og som hun, selv i den Fyrste Ayd, ikke havde", "om og som hun, selv i den største Nød, ikke havde"),
("og meente, at man ikke maatte bedomme hende for", "og meente, at man ikke maatte bedømme hende for"),
("omtalte Eders Fare og Redning for Køkkenpersonalet", "omtalte Eders Fare og Redning for Kjøkkenpersonalet"),
("paa Dcekket, naar hun var omgivet af Garden, dermed", "paa Dækket, naar hun var omgivet af Garden, der"),
("paa den smukkeste Maade. Fruen har taget sit Toi", "paa den smukkeste Maade. Fruen har taget sit Tøi"),
("paa den solvbeslagne Pibe.", "paa den sølvbeslagne Pibe."),
("paa tredive Aar med et koekt, men", "paa tredive Aar med et kækt, men"),
("plumpe Trcek.", "plumpe Træk."),
("over hans Ansigt, medens han halvhoit", "over hans Ansigt, medens han halvhøit"),
("og man horte det ralle i Halsen paa ham.", "og man hørte det ralle i Halsen paa ham."),
("og jeg har plaget D ig med min Heftighed! Jeg kan", "og jeg har plaget Dig med min Heftighed! Jeg kan"),
("og hendes Skjonhed, og man vovede undertiden at kalde", "og hendes Skjønhed, og man vovede undertiden at kalde"),
("mit Hjertelag. Frygt kun ej, at jeg render af", "mit Hjærtelag. Frygt kun ej, at jeg render af"),
("naar denne var kvrt ud, fik efterhaanden et vist", "naar denne var kørt ud, fik efterhaanden et vist"),
("ncermede sig Portechaisen mere og mere.", "nærmede sig Portechaisen mere og mere."),
("ncermeste Fiskerhytter gik frem og tilbage for at rense", "nærmeste Fiskerhytter gik frem og tilbage for at rense"),
("nogen af mine Damer. Froken Holstein er", "nogen af mine Damer. Frøken Holstein er"),
("nogen barnlig S ja l kan onske sig, hvilke jeg har", "nogen barnlig Sjæl kan ønske sig, hvilke jeg har"),
("nok, at et stort Hoved har en lille F orstand, men", "nok, at et stort Hoved har en lille Forstand, men"),
("nu rev Mo g e n s en Kniv fra Kaptajnen, ved hvis", "nu rev Mogens en Kniv fra Kaptainen, ved hvis"),
("og 'Astrid vovede ikke oftere at lade Vinduer", "og Astrid vovede ikke oftere at lade Vinduer"),
("og andet med mine gamle L ine, og onsler jeg gsiorne", "og andet med mine gamle Øjne, og ønsker jeg gjærne"),
("og ansaa sin lykkelige S tillin g som Resultatet af disse", "og ansaa sin lykkelige Stilling som Resultatet af disse"),
("og derfra kom Meddelelsen snart t il mig; men da jeg", "og derfra kom Meddelelsen snart til mig; men da jeg"),
("og er haabende, I finder Gjcestemildhed udi Danmark.", "og er haabende, I finder Gjæstemildhed udi Dan[- ]mark."),
("og hans Broder Astrad, ogsaa kaldet Torgunnce", "og hans Broder Astrad, ogsaa kaldet Torgunnæ"),
("rastlos op og ned ad G u lv e t... med Armene paa", "rastløs op og ned ad Gulvet. . . med Armene paa"),
("stro Virak for hendes Forfængelighed, ^tvoertimod, med", "strø Virak for hendes Forfængelighed, tværtimod, med"),
("reise kan der i mange Dage ikke vure Tale. Men", "reise kan der i mange Dage ikke være Tale. Men"),
("rynket og furet, som om aldrig Lykkens S o l havde", "rynket og furet, som om aldrig Lykkens Sol havde"),
("skimtede Fare for Opnaaelsen af sine Onsker og Fo rhaabninger", "skimtede Fare for Opnaaelsen af sine Ønsker og For[- ]haabninger"),
("skinsyg Storreparten af Solstraalerne i at komme", "skinsyg Størreparten af Solstraalerne i at komme"),
("smerteligt, ncesten lidenskabeligt: „H v o r jeg er vred", "smerteligt, næsten lidenskabeligt: „Hvor jeg er vred"),
("som gav en smigrende Jdee om Eierens", "som gav en smigrende Idee om Eierens"),
("som laa ved en kort Bro, stod en Fisker beskæftiget", "som laa ved en kort Bro, stod en Fisker beskjæftiget"),
("som lystelig puffede Eunucherne til S ide og stedse", "som lystelig puffede Eunucherne til Side og stedse"),
("sine klare j2jne ind i hans.", "sine klare Øjne ind i hans."),
("som netop fortsattes saaloenge, hun troede at", "som netop fortsattes saalænge, hun troede at"),
("spcendt Forventning stillede sig i Kreds omkring de tre,", "spændt Forventning stillede sig i Kreds omkring de tre,"),
("ssrget bedre for ham end Fru Stendal og Cornelia;", "sørget bedre for ham end Fru Stendal og Cornelia;"),
("staa aabne ved Nattetider. Lidt efter lid t svandt", "staa aabne ved Nattetider. Lidt efter lidt svandt"),
("stal ryste derved. Jeg veed nok, at de unge Piger", "skal ryste derved. Jeg veed nok, at de unge Piger"),
("stee, traf Dem her. Det er en sand Herlighed for", "skee, traf Dem her. Det er en sand Herlighed for"),
("store Trcrer inde i Aabningen, og det lykkedes", "store Træer inde i Aabningen, og det lykkedes"),
("sormprkedes med eet", "formørkedes med eet"),
("sin unge Hustru og den lille Son, hvormed deres dEgteskab", "sin unge Hustru og den lille Søn, hvormed deres Ægte[- ]skab"),
("sin Misbilligelse af hendes Forscet, og hemmeligt", "sin Misbilligelse af hendes Forsæt, og hemmeligt"),
("simpelt og grovt nd i de fine Hcender, hvis Fingre ere", "simpelt og grovt nd i de fine Hænder, hvis Fingre ere"),
("s. Er. Garrique. og lad Folk tro, at Du er Damefircederinde.", "f. Ex. Garrique, og lad Folk tro, at Du er Dame[- ]skræderinde."),
("saa havde hun dog en ubestemt Folelse af, at der", "saa havde hun dog en ubestemt Følelse af, at der"),
("saa have den Wre at byde dydsirede Jomfruen op til", "saa have den Ære at byde dydsirede Jomfruen op til"),
("saa kaster han Brevet tilbage til dets P lad s paa P u lte n ...", "saa kaster han Brevet tilbage til dets Plads paa Pulten. . ."),
("saa overvoeldende, at han forfattede et Frierbrev, saa", "saa overvældende, at han forfattede et Frierbrev, saa"),
("saa skal det snart blive godt igjen; thi der staacr", "saa skal det snart blive godt igjen; thi der staaer"),
("saa ud saa broget som en Skare Pappegojer, og", "saa ud saa broget som en Skare Pappegøjer, og"),
("saa vidt forgrenede Slcrgt bestandig er traadt i F amilieforbindelser", "saa vidt forgrenede Slægt bestandig er traadt i Fa[- ]milieforbindelser"),
("saae sig sporgende om, som om hun vilde udfinde", "saae sig spørgende om, som om hun vilde udfinde"),
("sad bonge grundende og sagde derpaa:", "sad længe grundende og sagde derpaa:"),
("sig ncevnet.", "sig nævnet."),
("sig ned, hoeldte han nogle Draaber af Flaskens I n d hold", "sig ned, hældte han nogle Draaber af Flaskens Ind[- ]hold"),
("sig t i l fuldtudsprungen Blomst have Knopperne", "sig til fuldtudsprungen Blomst have Knopperne"),
("siir P u n g i Sidsels Haand.", "sin Pung i Sidsels Haand."),
("blive hort.", "blive hørt."),
("„som jeg sogte, for at udbede mig en D a n d s", "„som jeg søgte, for at udbede mig en Dands"),
("bleven myrdet, som Abdul Pascha gcerne vilde have", "bleven myrdet, som Abdul Pascha gærne vilde have"),
("Liv. Og med hvilken Omhu og Kjurlighed blev", "Liv. Og med hvilken Omhu og Kjærlighed blev"),
("Lidt senere kom en H erre gaaende forbi Stedet;", "Lidt senere kom en Herre gaaende forbi Stedet;"),
("Lad for Guds Skyld Ingen mcerke, at", "Lad for Guds Skyld Ingen mærke, at"),
("Kys derpaa, idet hun udbrod:", "Kys derpaa, idet hun udbrød:"),
("Kvinde kan besidde denne Unde; hos Enkelte er den kun", "Kvinde kan besidde denne Ynde; hos Enkelte er den kun"),
("Kurv paa Ryggen. Hun fik lid t Beskæftigelse hist og", "Kurv paa Ryggen. Hun fik lidt Beskæftigelse hist og"),
("Krog, og bandt den lille Bylt Klceder sammen, som", "Krog, og bandt den lille Bylt Klæder sammen, som"),
("Kongen reiste sig. Hans Blik sogte efter Kirsten", "Kongen reiste sig. Hans Blik søgte efter Kirsten"),
("Konen betragtede ham opmcerksomt og sagde, idet", "Konen betragtede ham opmærksomt og sagde, idet"),
("Kjobenhavn itide; hun fulgte ham et Stykke udenfor", "Kjøbenhavn itide; hun fulgte ham et Stykke udenfor"),
("Jernfaste. Paa Hovedet havde han en opkrampet", "Jernfæste. Paa Hovedet havde han en opkram[- ]pet"),
("blevne enige om, hvem der skulde vcere Konge i Knuds", "blevne enige om, hvem der skulde være Konge i Knuds"),
("Lokkestj^orne staar paa Himlen, og jeg lommer da til", "Lykkestjærne staar paa Himlen, og jeg kommer da til"),
("Ig e n en S cen efo ran d rin g ... fra London til Konstantinopel.", "Igen en Sceneforandring. . . fra London til Kon[- ]stantinopel."),
("I et af de mindre, tilstodende Gemakker sad", "I et af de mindre, tilstødende Gemakker sad"),
("I det samme lod tunge, hurtige S k rid t ude paa", "I det samme lød tunge, hurtige Skridt ude paa"),
("I bedrog mig for Livets Lokke, og derfor hader jeg", "I bedrog mig for Livets Lykke, og derfor hader jeg"),
("I Fplelsen af, at han neppe selv af egen D r if t", "I Følelsen af, at han neppe selv af egen Drift"),
("Hun stirrede ud gennem G lasruderne i P ortechaisen,", "Hun stirrede ud gennem Glasruderne i Porte[- ]chaisen,"),
("Holm bukkede takkende, og E rn a sendte Etatsraaden", "Holm bukkede takkende, og Erna sendte Etatsraaden"),
("Hoffroken, og Geheimeraad von Osten og Grev", "Hoffrøken, og Geheimeraad von Osten og Grev"),
("Hjeelp derfra.", "Hjælp derfra."),
("Hjcelp, idet han sagde:", "Hjælp, idet han sagde:"),
("Himlen bevare Eder sor Kongens Vrede. Ulrik", "Himlen bevare Eder for Kongens Vrede. Ulrik"),
("Herrer og Gjcester, undskylde, at jeg saa pludselig har", "Herrer og Gjæster, undskylde, at jeg saa pludselig har"),
("Herre, som I seer ud til at vcere, pleier", "Herre, som I seer ud til at være, pleier"),
("Henrik lagde noillig sin Haand i Sidsels. Hun", "Henrik lagde uvillig sin Haand i Sidsels. Hun"),
("I seer ogsaa ud til at kunne vcerge Jer, hvis", "I seer ogsaa ud til at kunne værge Jer, hvis"),
("Lyden as deres milde Stemmer havde en", "Lyden af deres milde Stemmer havde en"),
("Lykken kan kjcele for efter Forgodtbefindende, uden at fordcerve", "Lykken kan kjæle for efter Forgodtbefindende, uden at for[- ]dærve"),
("M in Morfader, som var en polsk Adelsmand havde", "Min Morfader, som var en polsk Adelsmand havde"),
("S tra a le r ikke kunne troenge derigjennem. N a a r man", "Straaler ikke kunne trænge derigjennem. Naar man"),
("Ryggen, med bojet Hoved.", "Ryggen, med bøjet Hoved."),
("Rost.", "Røst."),
("Ringe kunde have forsynet hundrede Born med et", "Ringe kunde have forsynet hundrede Børn med et"),
("Rigdom og en saadan Moder maatte virke fladeligt,", "Rigdom og en saadan Moder maatte virke skadeligt,"),
("R an d u l vare disse Egenstaber ved N a tu r , Opdragelse", "Randul vare disse Egenskaber ved Natur, Opdragelse"),
("Plads i deres Samfundskredse, men jeg foretrcekker", "Plads i deres Samfundskredse, men jeg foretrækker"),
("Peders Beuediktinerkloster i Gent. Ledsaget af nogle", "Peders Benediktinerkloster i Gent. Ledsaget af nogle"),
("Paa denne Maade bleo det Ridderen for trangt", "Paa denne Maade blev det Ridderen for trangt"),
("P e te r i dybeste Forbavselse. „H ar du selv spekuleret", "Peter i dybeste Forbavselse. „Har du selv spekuleret"),
("Ogsaa Alvilda var dybt bevcrget, men hun", "Ogsaa Alvilda var dybt bevæget, men hun"),
("Nogle Minutter ester lykkedes det virkelig Brandt", "Nogle Minutter efter lykkedes det virkelig Brandt"),
("Noget som tynger Dig paa S indet; jeg gjentager:", "Noget som tynger Dig paa Sindet; jeg gjentager:"),
("Nogen vilde Jer tillivs under Troeerne, men hitte", "Nogen vilde Jer tillivs under Træerne, men hitte"),
("Nanna greb Kongens Haand og trykkede cl", "Nanna greb Kongens Haand og trykkede et"),
("Mgtefolkenes Omfavnelse.", "Ægtefolkenes Omfavnelse."),
("Men hun er jo ogsaa i Sorgedragt; thi ung som", "Men hun er jo ogsaa i Sørgedragt; thi ung som"),
("Mellemh^ide, og hans Bevægelser lette og smidige.", "Mellemhøide, og hans Bevægelser lette og smi[- ]dige."),
("Mcengden.", "Mængden."),
("Marie, medens dog en let Nodme for hen over hendes", "Marie, medens dog en let Rødme for hen over hen[- ]des"),
("Manden havde en Bondegaard i Fceste her i Omegnen,", "Manden havde en Bondegaard i Fæste her i Omegnen,"),
("Mand. Det var Fister Anders Stefensen og hans", "Mand. Det var Fisker Anders Stefensen og hans"),
("Mand, der pleier at scette Haardt mod Haardt,", "Mand, der pleier at sætte Haardt mod Haardt,"),
("Mand, Hustru og to B p rn , en Spn og en Datter.", "Mand, Hustru og to Børn, en Søn og en Datter."),
("Man kan ikke tage fejl af d e t... det er en T a n k e ...", "Man kan ikke tage fejl af det. . . det er en Tanke. . ."),
("Maade og ligesaa lydlos som han var kommen.", "Maade og ligesaa lydløs som han var kommen."),
("Ma n d Haanden og trykkede den varmt; „men derimod", "Mand Haanden og trykkede den varmt; „men derimod"),
("M o er Jansen! Jeg kan ikke give Hende mere, for", "Moer Jansen! Jeg kan ikke give Hende mere, for"),
("Havbugt og var som I s ved Bab-El-Mandeb.", "Havbugt og var som Is ved Bab-El-Mandeb."),
("Hat med Hogesjer paa Siden. Broder Viffert", "Hat med Høgefjer paa Siden. Broder Viffert"),
("Hans Hovede bojer sig dybere og dybere under", "Hans Hovede bøjer sig dybere og dybere under"),
("Han var altsaa i Ncerheden af hende. —", "Han var altsaa i Nærheden af hende. —"),
("Den unge Som and tilkastede hende et opmuntrende", "Den unge Sømand tilkastede hende et opmuntrende"),
("Den gamle Pavo kom sin Svigerdatter t il", "Den gamle Pavo kom sin Svigerdatter til"),
("Den ene ubedcekkede Haand var hvid og prydet med", "Den ene ubedækkede Haand var hvid og prydet med"),
("Datteren v il jeg kalde Margrethe.", "Datteren vil jeg kalde Margrethe."),
("Da Tjeneren var gaae«, faldt Greven i dybe", "Da Tjeneren var gaaet, faldt Greven i dybe"),
("Da Slotsporten lukkede sig efter hende, udstodte", "Da Slotsporten lukkede sig efter hende, udstødte"),
("D e r gled en tung Skygge hen over Moderens", "Der gled en tung Skygge hen over Moderens"),
("Byen. Han var munter og spogefuld, mere end han", "Byen. Han var munter og spøgefuld, mere end han"),
("Budskab til Fattigfolk, der ofte maa sulte og lide Nod", "Budskab til Fattigfolk, der ofte maa sulte og lide Nød"),
("Blik sporgende paa hende.", "Blik spørgende paa hende."),
("Blik og ncermede sig stedse mere og mere den elegante", "Blik og nærmede sig stedse mere og mere den elegante"),
("Bertha kunde ikke fremfors et Ord. Det var", "Bertha kunde ikke fremføre et Ord. Det var"),
("Bekostning. — Troellen har ved Sankt Bent ikke", "Bekostning. — Trællen har ved Sankt Bent ikke"),
("Beboerne af det lille landlige Hus iagttoge en storre", "Beboerne af det lille landlige Hus iagttoge en større"),
("Bcrgeret. „Livagtigt som om", "Bægeret. „Livagtigt som om"),
("Baronen, „a t heg tpr bande paa, jeg har tcendt et Lys", "Baronen, „at jeg tør bande paa, jeg har tændt et Lys"),
("B red d er, paa Herresædets Enemoerker, ere toet bevorede", "Bredder, paa Herresædets Enemærker, ere tæt be[- ]voxede"),
("B a r n , som F ru R a n d u l i sine Tanker altid kaldte", "Barn, som Fru Randul i sine Tanker altid kaldte"),
("Andre er den en efterloert Kunst — saaledes var den det sikkert", "Andre er den en efterlært Kunst — saaledes var den det sikkert"),
("Andet. Hvad der skilte Anton Hasting sra hende", "Andet. Hvad der skilte Anton Hasting fra hende"),
("Alvilda lcenede sig op mod ham og saa med", "Alvilda lænede sig op mod ham og saa med"),
("Adols Holstein og hans Familie kan ikke svigte", "Adolf Holstein og hans Familie kan ikke svigte"),
("Aars Forlob stod det Hele kun for hende som en", "Aars Forløb stod det Hele kun for hende som en"),
("Aandsretning saa lidet stemmer overeens med en cegte", "Aandsretning saa lidet stemmer overeens med en ægte"),
("A l denne Lykke blev dog pludselig forstyrret. Som", "Al denne Lykke blev dog pludselig forstyrret. Som"),
(":! noermede sig Holdepunktet.", "nærmede sig Høidepunktet."),
("' D u duer ikke engang til at pudse Solvtoiet ombord i", " Du duer ikke engang til at pudse Sølvtøiet ombord i"),
("Den yngste af Faders Brpdre er Philip Ludvig, der", "Den yngste af Faders Brødre er Philip Ludvig, der"),
("S trom m en mellem disse Troeer, der staae som en", "Strømmen mellem disse Træer, der staae som en"),
("Den, som sagde dette havde neppe udtalt, for han", "Den, som sagde dette havde neppe udtalt, før han"),
("Dermed gik han, fulgt af den G am les Velsignelser,", "Dermed gik han, fulgt af den Gamles Velsig[- ]nelser,"),
("Han stirrede lcenge paa Moderens forklarede", "Han stirrede længe paa Moderens forklarede"),
("Han rejser sig fra sin S to l og begynder at gaa", "Han rejser sig fra sin Stol og begynder at gaa"),
("Han har endnu ikke gennemløbet den forste Side,", "Han har endnu ikke gennemløbet den første Side,"),
("H an s Ledsager var nogle og fyrretyve", "Hans Ledsager var nogle og fyrretyve"),
("Gustav Adolf. Vi ville endog folge Grevindens", "Gustav Adolf. Vi ville endog følge Grevindens"),
("Geheimeraadinden forfcerdet.", "Geheimeraadinden forfærdet."),
("Fyr, hvis hele Ådre var alt Andet end tiltalende.", "Fyr, hvis hele Ydre var alt Andet end tiltalende."),
("Forsigtigt noermede jeg mig den vilde Klynge, da", "Forsigtigt nærmede jeg mig den vilde Klynge, da"),
("Forsigtighed end for. En vagtsom Hund blev anskaffet,", "Forsigtighed end før. En vagtsom Hund blev anskaf[- ]fet,"),
("Forlovelsen underrettede sin S vigerfader", "Forlovelsen underrettede sin Svigerfader"),
("Forholdet mellem hende og Moderen har n aturlig viis", "Forholdet mellem hende og Moderen har naturligviis"),
("Forhold imellem dem. Paula lcefte iv r ig , men der", "Forhold imellem dem. Paula læste ivrig, men der"),
("For mange Aar siden var denne morke Kvinde", "For mange Aar siden var denne mørke Kvinde"),
("Folkekjcer! Tak, Tak, for alt Godt!", "Folkekjær! Tak, Tak, for alt Godt!"),
("Flaske som indeholdt et grynt Fluidum og idet han bukkede", "Flaske som indeholdt et grønt Fluidum og idet han buk[- ]kede"),
("Faa Dage efter maatte han rejse for at voere i", "Faa Dage efter maatte han rejse for at være i"),
("F iguren var spinkel, snarere under end over", "Figuren var spinkel, snarere under end over"),
("Endelig, en sildig Aftenstund blev disse Folelser", "Endelig, en sildig Aftenstund blev disse Følelser"),
("En Bortfsrelse.", "En Bortførelse."),
("En Aften, det var forst i Marts, opstod der en", "En Aften, det var først i Marts, opstod der en"),
("Efter endt Maaltid noermede han sig et af de", "Efter endt Maaltid nærmede han sig et af de"),
("Eder for at erfare, boad der i Sksiobnens Bog staar", "Eder for at erfare, hvad der i Skjæbnens Bog staar"),
("E t Forsog paa at indrette et S o lu h r i Vindueskarmen", "Et Forsøg paa at indrette et Soluhr i Vindues[- ]karmen"),
("E n Pavse var opstaaet ved deres Komme,", "En Pavse var opstaaet ved deres Komme,"),
("Dronnings talrige tyske Slcegtninge,", "Dronnings talrige tyske Slægtninge,"),
("Dig paa en cerlig Maade. Jeg har faaet en Opfindelse", "Dig paa en ærlig Maade. Jeg har faaet en Opfindelse"),
("Det er et Vcerelse paa to smalle Fag, gjennem", "Det er et Værelse paa to smalle Fag, gjennem"),
("Det Hele kastede en Skygge over Glcrden, og", "Det Hele kastede en Skygge over Glæden, og"),
("Dengang den lille Sodreng begav sig til", "Dengang den lille Sødreng begav sig til"),
("Sidsel, „saasom faa as eders Lige bringe godt", "Sidsel, „saasom faa af eders Lige bringe godt"),
("Im id le rtid var Hasting dog ingenlunde as de I v rige", "Imidlertid var Hasting dog ingenlunde af de Iv[- ]rige"),
("Spor af paa hendes smukke Troek. Hun besad megen", "Spor af paa hendes smukke Træk. Hun besad megen"),
("Stigen, der forte til Loftet; lidt efter kom hun ned", "Stigen, der førte til Loftet; lidt efter kom hun ned"),
("af det rene, blaa Himmeldcekke. I en Baad,", "af det rene, blaa Himmeldække. I en Baad,"),
("af en Skruestik. Han var i et yderst flet Lune,", "af en Skruestik. Han var i et yderst slet Lune,"),
("Varme, hvormed Etatsraad en havde hilst paa Holm;", "Varme, hvormed Etatsraaden havde hilst paa Holm;"),
("Sponeck staa min Broders Hof for noer til, at jeg", "Sponeck staa min Broders Hof for nær til, at jeg"),
("Soren! Frida er den smukkeste Pige paa", "Søren! Frida er den smukkeste Pige paa"),
("af gode Christne, og indfluttede hverandre hver Aften", "af gode Christne, og indsluttede hverandre hver Aften"),
("afbrud.", "afbrød."),
("alene om i Haven eller sidde og spekulere inden D ore.", "alene om i Haven eller sidde og spekulere inden Døre."),
("Som Lynet fcrlder den kraftige Stamme, saaledes", "Som Lynet fælder den kraftige Stamme, saa[- ]ledes"),
("alflens Kryb er bleven uadskillelig forbunden hos mig,", "alskens Kryb er bleven uadskillelig forbunden hos mig,"),
("Solen spejlede sit glodende Aasyn i Mariagerfjord,", "Solen spejlede sit glødende Aasyn i Mariager[- ]fjord,"),
("angrebet, da de skulde tjene t il at berede", "angrebet, da de skulde tjene til at berede"),
("ankommet. Begge Skibe seilede ufortovet til Kjobenhavn,", "ankommet. Begge Skibe seilede ufortøvet til Kjø[- ]benhavn,"),
("at befinde mig i Selskab med Mennesker, derncest", "at befinde mig i Selskab med Mennesker, dernæst"),
("Stolthed og Hpiagtelse. Desuden, hvad kan Du have", "Stolthed og Høiagtelse. Desuden, hvad kan Du have"),
("at der sad en gammel Hund ved S id en af ham og", "at der sad en gammel Hund ved Siden af ham og"),
("Straahat og en Rejsetaske, hcengende i Rem over", "Straahat og en Rejsetaske, hængende i Rem over"),
("Svenden. „Er det ikke Eder, som er Bysoged eller", "Svenden. „Er det ikke Eder, som er Byfoged eller"),
("V illiam Lindal havde en h s i, kraftig Skikkelse,", "Villiam Lindal havde en høi, kraftig Skikkelse,"),
("Ungmeen paa Ternernes muntre Latter og livlige Tale,", "Ungmøen paa Ternernes muntre Latter og livlige Tale,"),
("Ved et lille Bord sad en oeldre og yngre", "Ved et lille Bord sad en ældre og yngre"),
("Venner kom hun t il Odense og vilde ved Nattetid", "Venner kom hun til Odense og vilde ved Nattetid"),
("Vi scrtte ham i en Stilling, saa at I snart kunne", "Vi sætte ham i en Stilling, saa at I snart kunne"),
("Trcek og et stort msrkebrunt Ska'g — kort sagt de", "Træk og et stort møkebrunt Skæg — kort sagt de"),
("Tone,. „Voer derfor taus, taus som den", "Tone, „Vær derfor taus, taus som den"),
("Tilsidesættelse kaldte Sammenligninger t i l Live, hvilke", "Tilsidesættelse kaldte Sammenligninger til Live, hvilke"),
("Tiggerkonen med den ynkeligste Betoning, bun kunde", "Tiggerkonen med den ynkeligste Betoning, hun kunde"),
("aabenbar havde Herredommct over sig. „Enhver", "aabenbar havde Herredømmet over sig. „Enhver"),
("af Troeet.", "af Træet."),
("Tanken om Onkel Peter, Orme, ^Edderkopper og", "Tanken om Onkel Peter, Orme, Ædderkopper og"),
("T o Mcend ncermede sig til B ordet. Den", "To Mænd nærmede sig til Bordet. Den"),
("Stykke som det, hun syer paa — men det er saa kjont,", "Stykke som det, hun syer paa — men det er saa kjønt,"),
("Slottet, fulgte to Mcend i nogen Afstand efter og", "Slottet, fulgte to Mænd i nogen Afstand efter og"),
("Vcegge, et Par Potteplanter, der staar i det ene Vindue,", "Vægge, et Par Potteplanter, der staar i det ene Vindue,"),
("at hun ikke mer undgik at trceffe sammen med ham,", "at hun ikke mer undgik at træffe sammen med ham,"),
("bjergede Foden, hvor hun kunde tigge den. Hendes", "bjergede Føden, hvor hun kunde tigge den. Hendes"),
("Slcegtskab saa ofte han saa Lejlighed dertil. Ja endog", "Slægtskab saa ofte han saa Lejlighed dertil. Ja endog"),
("beklagede paa sin sædvanlige ro lig e , overbærende", "beklagede paa sin sædvanlige rolige, overbærende"),
("bemeerkes saavidt, at hun blev knust. I den Anledning", "bemærkes saavidt, at hun blev knust. I den Anled[- ]ning"),
("bevoegede sig, begyndte at foette mindre Priis paa hende", "bevægede sig, begyndte at sætte mindre Priis paa hende"),
("betroede ham nu hviskende og i dyb F ortrolighed,", "betroede ham nu hviskende og i dyb Fortrolighed,"),
("Sind, der gjorde hende Sloegtskabet endnu ufordrageligere,", "Sind, der gjorde hende Slægtskabet endnu ufordrageligere,"),
("beskedent og a lv o rlig t, at det kunde vcere Model for", "beskedent og alvorligt, at det kunde være Model for"),
("at jeg ikke forgceves vilde henvende mig til Frederik", "at jeg ikke forgæves vilde henvende mig til Frederik"),
("Et Oieblik ester traadte. Robert ind med sin lille", "Et Øieblik efter traadte Robert ind med sin lille"),
("Enge ud imod Kattegattet strommer en A a , hvis", "Enge ud imod Kattegattet strømmer en Aa, hvis"),
("sprang op. „ P a p ir og P e n og Blcek — det skal", "sprang op. „ Papir og Pen og Blæk — det skal"),
("en Folge af, at Aanden heelt besjceler Materien; hos", "en Følge af, at Aanden heelt besjæler Materien; hos"),
("_ J o , de ere allesammen saa venlige! Tro", "— Jo , de ere allesammen saa venlige! Tro"),
("Drengen med at blive odelagt i B u n d og G rund.", "Drengen med at blive ødelagt i Bund og Grund."),
("Dronning Edele, om at komme t il ølandern. Hnv", "Dronning Edele, om at komme til Flandern. Hun"),
("Em il selv blev a lvorlig , men han vilde bortjage den", "Emil selv blev alvorlig, men han vilde bortjage den"),
("_ Og jeg vedbliver ncesten at tvivle derom,", "— Og jeg vedbliver næsten at tvivle derom,"),
("t il hendes Stab og t il den alene. Hertil kom noget", "til hendes Stab og til den alene. Hertil kom noget"),
("„Moder, Du gjor mig Uret. Sporg min Sproglærer", "„Moder, Du gjør mig Uret. Spørg min Sprog[- ]lærer"),
("A ar, noget hj-iere, halt paa det ene Ben, blond,", "Aar, noget høiere, halt paa det ene Ben, blond,"),
("Voer et en oerlig M and.", "været en ærlig Mand."),
("efterspore mine Veie, eller .taler D u et eneste Ord", "efterspore mine Veie, eller taler Du et eneste Ord"),
("syntes altid at vide, hvad han tramgte til. B lo t", "syntes altid at vide, hvad han trængte til. Blot"),
("t i l Ankers Fortcrlling, og Madam Norstrand", "til Ankers Fortælling, og Madam Norstrand"),
("tang, „fjceldent er jeg truffet paa Mcend af Eders", "taug, „sjældent er jeg truffet paa Mænd af Eders"),
("efter Liv, Bevcegelse, Handling! Vare Bvger vel nok", "efter Liv, Bevægelse, Handling! Vare Bøger vel nok"),
("t i l at udgjpre et helt Livs In d h o ld ? — Stillede Livet", "til at udgjøre et helt Livs Indhold? — Stillede Livet"),
("t il at reise sig paa mit Hoved, „fluide D u nogensinde", "til at reise sig paa mit Hoved, „skulde Du nogensinde"),
("A lt som Aarene gik voxede Margrethe op t i l den", "Alt som Aarene gik voxede Margrethe op til den"),
("t il nogen Moders Sjoel om, hvad jeg her har betroet", "til nogen Moders Sjæl om, hvad jeg her har be[- ]troet"),
("en Sosterson af F ru Host og kom derfor allerede som", "en Søstersøn af Fru Høst og kom derfor allerede som"),
("bemoerkede F ru Blohme. „Det er nobelt handlet", "bemærkede Fru Blohme. „Det er nobelt handlet"),
("Haar graanede, hendes Nakke boledes og Ild e n i", "Haar graanede, hendes Nakke bøiedes og Ilden i"),
("bleo et dagligt Malnrtba'ger for den milde F ru Karen.", "blev et dagligt Malurtbæger for den milde Fru Karen."),
("Haandmooen og more Mosteren t il Tidkort; men i", "Haandvæven og være Mosteren til Tidkort; men i"),
("saa maa jeg sonderflide D ig , saa maa jeg suge dit", "saa maa jeg sønderslide Dig , saa maa jeg suge dit"),
("et Mellemled, hvorved Froken v. Rohse blev", "et Mellemled, hvorved Frøken v. Röhse blev"),
("et Hovednik, „man stal ikke fceste Lid til alt hvad", "et Hovednik, „man skal ikke fæste Lid til alt hvad"),
("Guld og grpnne Skove i Overflpdighed, og som kan", "Guld og grønne Skove i Overflødighed, og som kan"),
("Vcext. Den vilde Flok tiltordnede ham B ifa ld ; men", "Væxt. Den vilde Flok tiltordnede ham Bifald; men"),
("satte sig ned paa Bcrnken hos Bysogden og saae hen til", "satte sig ned paa Bænken hos Byfogden og saae hen til"),
("satte sig ved B ordet ved S id en af Harmen.", "satte sig ved Bordet ved Siden af Harmen."),
("see, at D u er bleven endnu blegere, og det er m in", "see, at Du er bleven endnu blegere, og det er min"),
("selv har ikke T alent for Opdragelse, min Ven, D re n gen", "selv har ikke Talent for Opdragelse, min Ven, Dren[- ]gen"),
("sig ilde til Mode og ligesom sogte et Vcern mod det", "sig ilde til Mode og ligesom søgte et Værn mod det"),
("„Tak stal du have! T ro r du, det er klaret", "„Tak skal du have! Tror du, det er klaret"),
("sige t il sin Broderspn og Y n d lin g : „See!", "sige til sin Brodersøn og Yndling: „See!"),
("en ncesten bonkig Tone.", "en næsten bønlig Tone."),
("som han ivrigt syntes at gjennemlcrse. En Solvkande", "som han ivrigt syntes at gjennemlæse. En Sølvkande"),
("en Uge efter dette sit forste Besog var han forlovet", "en Uge efter dette sit første Besøg var han forlovet"),
("som de hyppige Vindstod foraarfagede i Hyttens", "som de hyppige Vindstød foraarsagede i Hyt[- ]tens"),
("som Huuslcerer hos en grevelig Famile p aa Landet, i", "som Huuslærer hos en grevelig Famile paa Landet, i"),
("Folk fortcelle. De, som holde til derinde, gjpr Jer", "Folk fortælle. De, som holde til derinde, gjør Jer"),
("Vinene, og som hvert Vieblik kunde vente fra deres", "Øinene, og som hvert Øieblik kunde vente fra deres"),
("Vilde Magnus derimod scette sig imod hendes Onskes", "Vilde Magnus derimod sætte sig imod hendes Ønskes"),
("skamkede han i Bcrgeret.", "skænkede han i Bægeret."),
("Forelobig skete der ingen Forandring i Frokenens", "Foreløbig skete der ingen Forandring i Frøkenens"),
("Ven dog muligviis havde Net i at tillcegge Onkelen", "Ven dog muligviis havde Ret i at tillægge Onkelen"),
("en let Sag, og Pengene ere dine. Paa cerlig Vis v il jeg", "en let Sag, og Pengene ere dine. Paa ærlig Vis vil jeg"),
("skinnet derpaa, hendes Vine gled glandslose hen", "skinnet derpaa, hendes Øine gled glandsløse hen"),
("truende H aanden i den R etning, de tvende Personer", "truende Haanden i den Retning, de tvende Personer"),
("tydst Skinder (Garver) var kun saa Alen fra Tyven", "tydsk Skinder (Garver) var kun faa Alen fra Tyven"),
("„E r det ikke Uret at fyre saadant et Liv som", "„Er det ikke Uret at føre saadant et Liv som"),
("dersom jeg vidste, at vi vilde mode en skjon", "dersom jeg vidste, at vi vilde møde en skjøn"),
("dersom hun vilde vente saalamge, tit de Danske vare", "dersom hun vilde vente saalænge, til de Danske vare"),
("— Jeg v il haabe derpaa, jeg v il stole paa Dig,", "— Jeg vil haabe derpaa, jeg vil stole paa Dig,"),
("— Men kan Du staffe mig Pengene t il rmorgen", "— Men kan Du skaffe mig Pengene til imorgen"),
("Dagen ester sad Professoren i sit Arbeidsvcerelse og", "Dagen efter sad Professoren i sit Arbeidsværelse og"),
("afprcegede denne tilsyneladende Ro i hans Idre;", "afprægede denne tilsyneladende Ro i hans Ydre;"),
("— Og Bprnene? afbrod Magnus sin Fader.", "— Og Børnene? afbrød Magnus sin Fader."),
("— T a l, jeg horer!", "— Tal, jeg hører!"),
("— og det fortanker jeg dem ikke i ; men derfor tager", "og det fortænker jeg dem ikke i; men derfor tager"),
("D ig , lader D u det mindste Vink eller Hentydning", "Dig, lader Du det mindste Vink eller Hentyd[- ]ning"),
("D en Kommende standsede, forundret over at hore", "Den Kommende standsede, forundret over at høre"),
("„ J a det kan D u svarge paa, og det saa Jorden", "„Ja det kan Du sværge paa, og det saa Jorden"),
("— I maa reise strar, det er aldeles nodvendigi", "— I maa reise strax, det er aldeles nødvendigt"),
("B lod og knuse hvert Been i D ig med disse mine", "Blod og knuse hvert Been i Dig med disse mine"),
("D e pvrige Tilstedeværende besvarede F ilip s", "De øvrige Tilstedeværende besvarede Filips"),
("D a T horning var kommen nogle Skridt bort,", "Da Thorning var kommen nogle Skridt bort,"),
("Crna om det nye Kald, han snart skulde tiltrcede, da", "Erna om det nye Kald, han snart skulde tiltræde, da"),
("an! In g en af J e r er dog tjent med, at han bliver", "an! Ingen af Jer er dog tjent med, at han bliver"),
("Brandt sorspgte at rejse sig, men han formanede", "Brandt forsøgte at rejse sig, men han formaaede"),
("„Den svenske Ministerresident Fegrceus besogte", "„Den svenske Ministerresident Fegræus besøgte"),("den Helliges Drab og strax skikket Bud t il sin Sysler,", "den Helliges Drab og strax skikket Bud til sin Søster,"),
("D e r vexledes aldrig et Kjcertegn mellem Mo d e r og", "Der vexledes aldrig et Kjærtegn mellem Moder og"),
("tumle dem saa lcenge. V i blive jo ikke heller mere", "tumle dem saa længe. Vi blive jo ikke heller mere"),
("at rpgte Faderens lille Kvceghjord.", "at røgte Faderens lille Kvæghjord."),
("af skrevne T a l har viist sig aldeles haablost.", "af skrevne Tal har viist sig aldeles haabløst."),
("de stojende Somcend, og selv som Som and?", "de støjende Sømænd, og selv som Sømand?"),
("ubetinget; ukjendte, fjcernt-boende Froender bleve", "ubetinget; ukjendte, fjærnt-boende Frænder bleve"),
("ud til Havet. F orbi G aarden og gjennem disse", "ud til Havet. Forbi Gaarden og gjennem disse"),
("Doktoren. „B liv er det ved paa den M aad e, ender", "Doktoren. „Bliver det ved paa den Maade, ender"),
("uhyggelige Folelse og udbrod: „Hvad vedkommer i", "uhyggelige Følelse og udbrød: „Hvad vedkommer i"),
("Dog var det neppe Slovhed eller Tankeloshed, der", "Dog var det neppe Sløvhed eller Tankeløshed, der"),
("undertiden bevoegedes hans Lceber, som om han", "undertiden bevægedes hans Læber, som om han"),
("ung Mand, hvis Billed har prcrget sig i dit S in d ?", "ung Mand, hvis Billed har præget sig i dit Sind?"),
("Agnes; men der blev svrget for hendes Fo rn ø d en heder,", "Agnes; men der blev sørget for hendes Fornøden[- ]heder,"),
("Djne spvrgende rettet mod sig, og han holdt", "Øjne spørgende rettet mod sig, og han holdt"),
("var aldeles urykkelig vg mindedes tillig e , ved B a ro n essens", "var aldeles urykkelig og mindedes tillige, ved Baron[- ]essens"),
("var der lagt scerlig an paa at saa Hasting", "var der lagt særlig an paa at faa Hasting"),
("var dog øjeblikke, hvor hun syntes, alt var mprkt og", "var dog Øjeblikke, hvor hun syntes, alt var mørkt og"),
("var klcrdt i en blaa Kofte, med et bredt, brunt Bcrlte", "var klædt i en blaa Kofte, med et bredt, brunt Bælte"),
("— God K v eld , F ilip , svarede denne alvorlig.", "— God Kveld, Filip, svarede denne alvorlig."),
("var meget mFrk, med et P a r sorte, spillende", "var meget mørk, med et Par sorte, spillende"),
("Det er ogsaa kun et F o rso g ... thi hans Ojne har", "Det er ogsaa kun et Forsøg. . . thi hans Øjne har"),
("vcenne hende til uophsrligt Arbejde.", "vænne hende til uophørligt Arbejde."),
("ved Helsingor, hvortil et mindre Fartoi alt var", "ved Helsingør, hvortil et mindre Fartøi alt var"),
("Det blev umuligt for min Fatter at fortsatte sine", "Det blev umuligt for min Fætter at fortsætte sine"),
("ved hans O rd . „ J a , P e t e r , jeg er forsigtig, og for", "ved hans Ord. „Ja, Peter, jeg er forsigtig, og for"),
("deu storste Del af Nullerne. Men trods det syntes", "den største Del af Nætterne. Men trods det syntes"),
("Der oar ensomt paa Borgen for Jom fru Anna.", "Der var ensomt paa Borgen for Jomfru Anna."),
("Denne udstodte en Lyd, som om han skulde kvceles,", "Denne udstødte en Lyd, som om han skulde kvæles,"),
("Ånde; men den Unde, som i Grunden kun den modnere", "Ynde; men den Ynde, som i Grunden kun den modnere"),
("„J a , Gud jke Lov, at jeg blev bevaret for Dig,", "„Ja, Gud ske Lov, at jeg blev bevaret for Dig,"),
("det ikke. Han kravlede paa Hcrnder og Fodder hen til", "det ikke. Han kravlede paa Hænder og Fødder hen til"),
("Alle snege sig hen under Troeet. Nogle Nieblikke", "Alle snege sig hen under Træet. Nogle Øieblikke"),
("Side han sav, og svor paa, at den Forste, der vovede", "Side han sad, og svor paa, at den Første, der vovede"),
("sceldet. Forholdet t il Hasting blev koligt i den persiske", "fældet. Forholdet til Hasting blev køligt i den per[- ]siske"),
("Marmortropper, steg de to Mcend ned i en Vevcertuingskjcelder,", "Marmortrapper, steg de to Mænd ned i en Bevært[- ]ningskjælder,"),
("lod gjennem Skorfteenshullet.", "lød gjennem Skorsteenshullet."),
("Mcend, ere stegne i Land udi Helsingor. Eftersom de", "Mænd, ere stegne i Land udi Helsingør. Eftersom de"),
("„et L iv , der er aldeles unyttigt og betydningslvst?", "„et Liv, der er aldeles unyttigt og betydningsløst?"),
("lukkede G ra v , og frels mig derved fra at cede", "lukkede Grav, og frels mig derved fra at æde"),
("Med spamdt Opmwrksomled lyttede den lille F a milie", "Med spændt Opmærksomhed lyttede den lille Fa[- ]milie"),
("Somanden var Alexander, Lcegen, hendes Alt paa", "Sømanden var Alexander, Lægen, hendes Alt paa"),
("l^onge nok til, at Frn Vibekkes elskede drog Munkekappen", "længe nok til, at Fru Vibekkes elskede drog Munkekap[- ]pen"),
("Som berprt as en elastisk Fjeder sprang hele", "Som berørt af en elastisk Fjeder sprang hele"),
("kunde faa Lejlighed t i l at folge hende hjem, og under", "kunde faa Lejlighed til at følge hende hjem, og under"),
("kulorte Crickethuer, der fremtoges paa Soen,", "med kulørte Crickethuer, der fremtoges paa Søen,"),
("langt mere oedel og ridderlig Teenkemaade. ^evnne sti", "langt mere ædel og ridderlig Tænkemaade. Senere fik"),
("Son Soren.", "Søn Søren."),
("Vcegten af de Tanker der gennemfarer d e t... hans", "Vægten af de Tanker der gennemfarer det. . . hans"),
("Soren var hans Broder. Han tcenkte aldrig paa at skyde", "Søren var hans Broder. Han tænkte aldrig paa at skyde"),
("give Afkald paa den Haandsrakning, vi h id til havde", "give Afkald paa den Haandsrækning, vi hidtil havde"),
("men kold og afmaalt, som hendes Hjcerte og Vcesen.", "men kold og afmaalt, som hendes Hjærte og Væsen."),
("give sin Stem m e. „Jeg er den gamle T rine Jansen,", "give sin Stemme. „Jeg er den gamle Trine Jansen,"),
("men enhver vidste jo, at han var en Daglejers Son og", "men enhver vidste jo, at han var en Dagleiers Søn og"),
("meget, saa stikke vi selv i Soen med en anselig Estadre", "meget, saa stikke vi selv i Søen med en anselig Eskadre"),
("Stemme ham ind i Dret, hils din fordpmte Herre og", "Stemme ham ind i Øret, hils din fordømte Herre og"),
("Længden oar dette dog ikke rosomt nok. Hellere herte", "Længden var dette dog ikke rosomt nok. Hellere hørte"),
("med lybjte Dirik,", "med lybske Dirik."),
("Sted. Edele modtog med Glcede dette Tilbu d og drog", "Sted. Edele modtog med Glæde dette Tilbud og drog"),
("M u r til begge S id e r , i den hoitidelige Dunkelhed,", "Mur til begge Sider, i den høitidelige Dunkelhed,"),
("med at gjore Sejlene klare. Lange Ncrt vare udspændte", "med at gjøre Sejlene klare. Lange Næt vare ud[- ]spændte"),
("han fvor paa, at jeg skulde sige hain, om jeg virkelig", "han svor paa, at jeg skulde sige ham, om jeg virkelig"),
("mange i lignende S tillin g , og i Spoending afventede", "mange i lignende Stilling, og i Spænding afventede"),
("maaste Kjcerlighed, der har fundet Vei til dit unge,", "maaske Kjærlighed, der har fundet Vei til dit unge,"),
("kommet t i l Ven med et spcedt Barn hcengende i en", "kommet til Øen med et spædt Barn hængende i en"),
("kommer det, at Slcegtens unge Mcend, saavidt jeg har", "kommer det, at Slægtens unge Mænd, saavidt jeg har"),
("komme dygtig paa Landet. D u maa selv fore ham", "komme dygtig paa Landet. Du maa selv føre ham"),
("kjcerlige Blikke og paa hendes Spprgsmaal om den", "kjærlige Blikke og paa hendes Spørgsmaal om den"),
("hvorved den sidste moerkede, at hendes S tillin g ikke", "hvorved den sidste mærkede, at hendes Stilling ikke"),
("hvorpaa der laa nogle Boger og en Mcrngde Brevskaber,", "hvorpaa der laa nogle Bøger og en Mængde Brevskaber,"),
("Skjsnhed beromte Dorothea Sophia, Prinsesse af", "Skjønhed berømte Dorothea Sophia, Prinsesse af"),
("hvor de ellers fcerdedes, traadte han kun t il paa udtrykkelig", "hvor de ellers færdedes, traadte han kun til paa udtrykke[- ]lig"),
("Skilling. — Nei, lad mig see! J a , saa G ud troer", "Skilling. — Nei, lad mig see! Ja, saa Gud troer"),
("hvilken RuSmuS Nielsen iil Atmegaard omsider", "hvilken Rasmus Nielsen til Almegaard omsider"),
("hvilke In strum en ter der v ar fornodne til at udfore", "hvilke Instrumenter der var fornødne til at udføre"),
("hverve saa mange Folk som muligt, jeg fial lonne", "hverve saa mange Folk som muligt, jeg skal lønne"),
("hvad der er skeel. Og hvad det angaaer at gjore os", "hvad der er skeet. Og hvad det angaaer at gjøre os"),
("S o n af Vild- og Rhingreve i Morchingen, Jo h an", "Søn af Vild- og Rhingreve i Mørchingen, Johan"),
("holdt opmcerksomt Die med ham og dengang den", "holdt opmærksomt Øie med ham og dengang den"),
("hilsede den Jndtrcedende med det samme kjcerlige B lik ,", "hilsede den Indtrædende med det samme kjærlige Blik,"),
("hendes benede Skikkelse hcevede sig; hun udstrakte", "hendes bøiede Skikkelse hævede sig; hun udstrakte"),
("her fra Egnen, vi fial snart vise Roverne hvad vi ere", "her fra Egnen, vi skal snart vise Røverne hvad vi ere"),
("Selskabet op og var med stum Gloede Vidne t il", "Selskabet op og var med stum Glæde Vidne til"),
("hellere gik hun i Rosenlund at hore Fnglekoidder eller", "hellere gik hun i Rosenlund at høre Fuglekvidder eller"),
("heller at vcere den Forste, der bryder Forbundet,", "heller at være den Første, der bryder Forbundet,"),
("Skulderen, kom gaaende og stansede et Djeblik forat", "Skulderen, kom gaaende og stansede et Øjeblik for"),
("Morket har scenket sig ned over Halvmaanens By,", "Mørket har sænket sig ned over Halvmaanens By,"),
("kcempet mod Opryrerne, havde tilbudt den ulykkelige", "kæmpet mod Oprørerne, havde tilbudt den ulykkelige"),
("hans beromte Navne, Holger Danste, der sad hos", "hans berømte Navne, Holger Danske, der sad hos"),
("Ncerhed, krcenkede ham og avlede en Bitterhed i hans", "Nærhed, krænkede ham og avlede en Bitterhed i hans"),
("jeg ikke, at det er en M ark! — D et er dog en", "jeg ikke, at det er en Mark! — Det er dog en"),
("Nogen Tid forlob, da bevoegede Krattet sig", "Nogen Tid forløb, da bevægede Krattet sig"),
("Noget at takke for; thi der kan vcere Tilfoelde, hvor", "Noget at takke for; thi der kan være Tilfælde, hvor"),
("Nu kom Tjeneren med den tcendte Lampe. Vcerelset", "Nu kom Tjeneren med den tændte Lampe. Værelset"),
("Opfyldelse, var hendes Kjcerlighed t il ham stor", "Opfyldelse, var hendes Kjærlighed til ham stor"),
("har vceret Lcerer ved Almueskolerne, har sit", "har været Lærer ved Almueskolerne, har sit"),
("P e te r! S a a skal jeg sige dig det. F o r det hedder", "Peter! Saa skal jeg sige dig det. For det hedder"),
("i nogen T id har ladet sig glide i en B aad ned med", "i nogen Tid har ladet sig glide i en Baad ned med"),
("i disse trange Tider, da store Herrer rioes som Uloe", "i disse trange Tider, da store Herrer rives som Ulve"),
("i deres Aftenbpn. Spnnen, troer jeg, hed Diderik og", "i deres Aftenbøn. Sønnen, troer jeg, hed Diderik og"),
("Lcerere om nogen af dem har Aarsag t il at beklage", "Lærere om nogen af dem har Aarsag til at beklage"),
("han opgiver Forsoget paa at freske sine Tanker til dets", "han opgiver Forsøget paa at fæske sine Tanker til dets"),
("om I havde mcegtige Frcender, der kunde skytte Eder", "om I havde mægtige Frænder, der kunde skytte Eder"),
("fle, sagde Grevinden sorgmvdig.", "ske, sagde Grevinden sørgmodig."),
("og F lid , som er folgevcerdig; men hos F ru", "og Flid, som er følgeværdig; men hos Fru"),
("paa og spolede sig og sin S o rg i et .Kloster. Hun", "paa og fjælede sig og sin Sorg i et Kloster. Hun"),
("paa mig selv! hvor jeg har vcrret egenkjcerlig og", "paa mig selv! hvor jeg har været egenkjærlig og"),
("og allerede en M aaned efter gift med den skjonne,", "og allerede en Maaned efter gift med den skjønne,"),
("og bemcerkede snart en hoj, bleg S om and,", "og bemærkede snart en høj, bleg Sømand,"),
("I hore til Adelen, men optrced saa simpelt og tarveligt", "I høre til Adelen, men optræd saa simpelt og tarve[- ]ligt"),
("Hun folie Blodet stromme tilbage til Kinderne,", "Hun følte Blodet strømme tilbage til Kinderne,"),
("og skjont Kandidaten helst vilde have vwret fri, havde", "og skjønt Kandidaten helst vilde have været fri, havde"),
("paa det as Junker Christian omtalte S lo t Beck, som", "paa det af Junker Christian omtalte Slot Beck, som"),
("og halsbrækkende Ja g t ret oar hans Lyst, og paa en", "og halsbrækkende Jagt ret var hans Lyst, og paa en"),
("Her udsogte han et bekvemt Soede, bandt sig fast", "Her udsøgte han et bekvemt Sæde, bandt sig fast"),
("I et Hjorne af Vcerelset sad en gammel Kvinde", "I et Hjørne af Værelset sad en gammel Kvinde"),
("I d a Krabbe som ZEgtefolk. — D a IGrubbe strax efter", "Ida Krabbe som Ægtefolk. — Da Grubbe strax efter"),
("og loengst bortliggende Steder. H id til er det", "og længst bortliggende Steder. Hidtil er det"),
("Uleilighed, da maa De slet ikke tcenke derpaa! — V i", "Uleilighed, da maa De slet ikke tænke derpaa! — Vi"),
("formaaede at gjore os t il Behag, troede at maatte", "formaaede at gjøre os til Behag, troede at maatte"),
("nsisomme Liv. T id t og mange Gange har Dristet", "nøisomme Liv. Tidt og mange Gange har Ønsket"),
("Tiden maatte serge for sig selv. Me d dette M a a l", "Tiden maatte sørge for sig selv. Med dette Maal"),
("Synner, der hiin skjcebnesvangre Nide J u li havde", "Sønner, der hiin skjæbnesvangre 10de Juli havde"),
("mig. Hvorfor stal jeg altid tvinges t il at bestjceftige", "mig. Hvorfor skal jeg altid tvinges til at beskjæftige"),
("om lid t mere S o l lydt indenfor den lille Dagligstues", "om lidt mere Sol lydt indenfor den lille Dagligstues"),
("min Hustru og celdste Datter at faae en Syg at sorge", "min Hustru og ældste Datter at faae en Syg at sørge"),
("fine Ejendomme og har taget Ravn efter Slottet. —", "sine Ejendomme og har taget Navn efter Slottet. —"),
("proegtig F y r. den Thorning! Gid nu Djcevelen", "prægtig Fyr, den Thorning! Gid nu Djævelen"),
("gamle, provede Kammertjener Abro, samt min forste", "gamle, prøvede Kammertjener Abro, samt min første"),
("fjoernet fra Baronessen og oftere folie sig delvis overf", "fjærnet fra Baronessen og oftere følte sig delvis over[- ]flødig."),
("fra sit Forscet og erkjendte, at det var Himlens Vilkie,", "fra sit Forsæt og erkjendte, at det var Himlens Villie,"),
("ncrste Sekund blev Doren aabnet haardt, og Hustruen", "næste Sekund blev Døren aabnet haardt, og Hustruen"),
("for hans Lyst t il at spise Gaasesteg pna Andres", "for hans Lyst til at spise Gaasesteg paa Andres"),
("nok t il at bringe hende t il at afstaa derfra; men", "nok til at bringe hende til at afstaa derfra; men"),
("for et Oieblik sormprkede hans Aasyn, idet han pludselig", "for et Øieblik formørkede hans Aasyn, idet han pludselig"),
("og tankefuld sin Moders blege Trcrk; da udbrod hun", "og tankefuld sin Moders blege Træk; da udbrød hun"),("Bakker omgive G aarden mod N o rd , S y d og Vest;", "Bakker omgive Gaarden mod Nord, Syd og Vest;"),
("har ikke drevet det hsiere end t i l at scette Knop, udvikle", "har ikke drevet det høiere end til at sætte Knop, ud[- ]vikle"),
("Brandis Ore og hviskede folgende Ord til ham:", "Brandts Øre og hviskede følgende Ord til ham:"),
("siken uden at grcede. S id en den T id lufter han af,", "siken uden at græde. Siden den Tid lufter han af,"),
("Sloegtskabet fra sig, men onskede kun at hoeve ham opad", "Slægtskabet fra sig, men ønskede kun at hæve ham opad"),
("isort en ny lysebruu Kofte, kantet med Odderskiud", "iført en ny lysebrun Kofte, kantet med Odderskind"),
("ostenfor den strcekke sig derimod groesrige Enge helt", "østenfor den strække sig derimod græsrige Enge helt"),
("P a a dette Herresoede boede nu E iler Grubbe og", "Paa dette Herresæde boede nu Eiler Grubbe og"),
("Soeben, thi Legemet er jo eders, 2 eouer dog ej at omdanne", "Svøben, thi Legemet er jo eders, I evner dog ej at om[- ]danne"),
("at lcrgge Haand paa mig, skulde hore ham t il.", "at lægge Haand paa mig, skulde høre ham til."),
("Doren til det ncrste Vaerelse blev holdt paa Klem.", "Døren til det næste Værelse blev holdt paa Klem."),
("paa Oborg, hoor hendes Bitterhed mod Mennestene", "paa Øborg, hvor hendes Bitterhed mod Menneskene"),
("Hans Kjorbo var en as disse oedle Naturer, som", "Hans Kjørbo var en af disse ædle Naturer, som"),
("dEnder. Harald v il meget mod min V illie faae", "Ænder. Harald vil meget mod min Villie faae"),
("S tillin g , men da den noevnte Slcegtning kom og blev", "Stilling, men da den nævnte Slægtning kom og blev"),
("paany, Bustene stiltes og et morkt Ansigt kom", "paany, Buskene skiltes og et mørkt Ansigt kom"),
("S ted er danne et saa toet Lovtag over Aaen, at S o le n s", "Steder danne et saa tæt Løvtag over Aaen, at Solens"),
("S tand, mine Herrer P rinser, der have vceret saa godt", "Stand, mine Herrer Prinser, der have været saa godt"),
("Gloede, og Hjertet soler sig mildt bevoeget ved dette", "Glæde, og Hjertet føler sig mildt bevæget ved dette"),
("Angste syntes at vcere 25 A ar gammel. Han", "Yngste syntes at være 25 Aar gammel. Han"),
("hun udstrakte H aanden: „E n lille Skilling i G uds", "hun udstrakte Haanden: „En lille Skilling i Guds"),
("Gloder, skottende Hovedet med begge Hoender.", "Gløder, støttende Hovedet med begge Hænder."),
("hvilket jeg foler, v il skee med grordende Taarer,", "hvilket jeg føler, vil skee med grædende Taarer,"),
("hendes hoieste Snfle at salge med Svigerforceldrene.", "hendes høieste Ønske at følge med Svigerforældrene."),
("hvor han havde foerdedes, appellerede t il deres noere", "hvor han havde færdedes, appellerede til deres nære"),
("segte Urtegaarden, hoor Urternes Trivsel ret oar", "søgte Urtegaarden, hvor Urternes Trivsel ret var"),
("saadan Jagt mistede han Lioet. H r. Jens leoede dog", "saadan Jagt mistede han Livet. Hr. Jens levede dog"),
("„M e n D u maa lade H r. Engberg have Ro nu,", "„Men Du maa lade Hr. Engberg have Ro nu,"),
("Trcek, som endnu i Dyden smilede venlig t il ham,", "Træk, som endnu i Døden smilede venlig til ham,"),
("altid bleve t il Fordel for H r. Saffer. Folgen blev,", "altid bleve til Fordel for Hr. Saffer. Følgen blev,"),
("for — en rigtig foielig S yg , som v il folge alle deres", "for — en rigtig føielig Syg , som vil følge alle deres"),
("og flyde, lad ham slaas med gode V enner, om D u", "og skyde, lad ham slaas med gode Venner, om Du"),
("desvarre almindelige. At bedomme dem retfardigt er", "desværre almindelige. At bedømme dem retfærdigt er"),
("— Horte Du, Ib ? udbrod han; Faelden faldt", "— Hørte Du, Ib? udbrød han; Fælden faldt"),
("og et Bcrger stod paa det ene Hjorne as Bordet, og", "og et Bæger stod paa det ene Hjørne af Bordet, og"),
("strcebsom ung Man d , hvis personlige Bekjendtflab det", "stræbsom ung Mand, hvis personlige Bekjendtskab det"),
("og Tyvekncegt paa F y n og Langeland. H ar du", "og Tyveknægt paa Fyn og Langeland. Har du"),
("Der forlober M in u tte r... K v a rte re r... og bestandig", "Der forløber Minutter. . . Kvarterer. . . og be[- ]standig"),
("han stal vcere retfcerdig.", "han skal være retfærdig."),
("Soren var en skrutrygget, skeloiet og rodhaaret", "Søren var en skrutrygget, skeløiet og rødhaaret"),
("ved Rang eller Formue at voere sig vcerdig. Meu den", "ved Rang eller Formue at være sig værdig. Men den"),
("Dronning at syre hende og hendes ^Lyn E a rl t il Flandern,", "Dronning at føre hende og hendes Søn Earl til Flandern,"),
("vare gaacde. D a hun endelig havde udtom t sig,", "vare gaaede. Da hun endelig havde udtømt sig,"),
("ham ril S vigersøn. Lybske D irik kar aldrig", "ham til Svigersøn. Lybske Dirik har aldrig"),
("med hoje Troeer, hvilke om S om ren paa mange", "med høje Træer, hvilke om Somren paa mange"),
("uok sorge fo r , men Forhusets M u r hindrer", "nok sørge for, men Forhusets Mur hindrer"),
("tor indvie Komtesse ^Sponeck eller Froken von Osten", "tør indvie Komtesse Sponeck eller Frøken von Osten"),
("L y n fare knittrende fra Himmel t i l J o rd , saaledes", "Lyn fare knittrende fra Himmel til Jord, saaledes"),
("oedle. Haar og Overskceg lysebrunt og meget soigneret.", "ædle, Haar og Overskæg lysebrunt og meget soigneret."),
("Men der slog et cergjerrigt Hjcerte under Sorens", "Men der slog et ærgjerrigt Hjærte under Sørens"),
("— Jeg er slet ikke fornoiet med D ig , min Son", "— Jeg er slet ikke fornøiet med Dig , min Søn"),
("„D e t er knap n o k ,.............du kan ikke undvcere", "„Det er knap nok, . . . . . du kan ikke undvære"),
("Lad ham lcere at blive en rafl D reng, lad ham sejle", "Lad ham lære at blive en rask Dreng, lad ham sejle"),
("som dannes as de morkegronne Hvoelvinger, og man", "som dannes af de mørkegrønne Hvælvinger, og man"),
("lcegge Mcerke til hendes Bevcegelser, han havde indtaget", "lægge Mærke til hendes Bevægelser, han havde ind[- ]taget"),
("„ P i l nu af saa godt dine Ben have lcert D ig !", "„Pil nu af saa godt dine Ben have lært Dig!"),
("„ J a hvem h ar ikke det! Den storste Gavtyv", "„Ja hvem har ikke det! Den største Gavtyv"),
("viste, at han horte t i l de hojere Samfundsklasser.", "viste, at han hørte til de højere Samfundsklasser."),
("— S lavinde, fordsmte Hund, S lavinde! raabte en", "— Slavinde, fordømte Hund, Slavinde! raabte en"),
("Hvad Djcevelen skulde jeg ogsaa vcere rced for? —", "Hvad Djævelen skulde jeg ogsaa være ræd for? —"),
("og strog med kjcrrtegnende Vinhed det morke", "og strøg med kjærtegnende Ømhed det mørke"),
("D et kan ikke hjcrlpe, at han D ag ud og D ag ind", "Det kan ikke hjælpe, at han Dag ud og Dag ind"),
("jeg stal strap skrive t i l Deres Fader og fortulle ham,", "jeg skal strax skrive til Deres Fader og fortælle ham,"),
("morte Gaader og sige et Menneske, boor bojt bans", "mørke Gaader og sige et Menneske, hvor højt hans"),
("sidde h er, have ljendt og agi et din salig Foder.", "sidde her, have kjendt og agtet din salig Fader."),
("D ine, sort H aar, en mFrk, solbrcrndt Hudfarve.", "Øine, sort Haar, en mørk, solbrændt Hudfarve."),
("og oolde alskens M on og Ustvr. Men boad bringer", "og volde alskens Mén og Ustyr. Men hvad bringer"),
("vceneste Ungmp, nogen kunde se fo r sine Ojne, og", "væneste Ungmø, nogen kunde se for sine Øjne, og"),
("han Tilnavnet S t. Georgs Syn. 9Ned dyb Bedryvelse", "han Tilnavnet St. Georgs Søn. Med dyb Bedrøvelse"),
("paa Borgen, han hordedes i de store Skooe, hoor oild", "paa Borgen, han færdedes i de store Skove, hvor vild"),
("fro s , og saa kunde han ikke lamger hore paa M u -", "frøs, og saa kunde han ikke længer høre paa Mu-"),
("for D ig , hvis Glands skjcerer D ig i Dinene. Regningen", "for Dig, hvis Glands skjærer Dig i Øinene. Reg[- ]ningen"),
("tankelos! D u sagde, at D u folte D ig tung og trcrt,", "tankeløs! Du sagde, at Du følte Dig tung og træt,"),
("(ttaarde, nej. H r. Ridder, jeg stal oel gjore eder Pinen", "Gaarde, nej, Hr. Ridder, jeg skal vel gjøre eder Pinen")]

    @parameterized.parameterized.expand(testcases)
    def test_align_len(self, orig, corr):
        """Test whether length of aligned original line == length of correct line."""
        alignment = align_ocr(orig, corr)
        origtup = alignment.aligned_orig
        corrtup = alignment.correct
        if len(origtup) != len(corrtup):
            print('Failed: test_align_len')
            print('Orig:', orig)
            print('Corr:', corr)
            print(alignment)
            print()
        self.assertEqual(len(origtup), len(corrtup))

    @parameterized.parameterized.expand(testcases)
    def test_align_len2(self, orig, corr):
        """Test whether length of aligned original line == length of unaltered, tokenized correct line."""
        alignment = align_ocr(orig, corr)
        if len(alignment.aligned_orig) != len(alignment.correct):
            print('Failed: test_align_len2')
            print('Correct tokens:', alignment.correct)
            print('Aligned correct:', alignment.correct)
            print('Aligned original:', alignment.aligned_orig)
            print(alignment)
            print()
        self.assertEqual(len(alignment.aligned_orig), len(alignment.correct))

    @parameterized.parameterized.expand(testcases)
    def test_matches(self, orig, corr):
        """Test whether matches do indeed match."""
        def matches_match(alignm):
            def is_match(origtok, corrtok):
                # If the correct token is itself a hyphen, test whether the origial might be too.
                if corrtok == '[-]':
                    matchval = bool(origtok == corrtok)
                # Hyphenated words: If first part matches original, consider it a match.
                elif '[-]' in corrtok:
                    matchval = origtok.startswith(corrtok.split('[-]')[0])
                else:
                    matchval = bool(origtok == corrtok)
                return matchval

            triples = list(zip(alignm.aligned_orig, alignm.correct, alignm.matches))
            matches = [is_match(o, c) == m for o, c, m in triples]
            return matches

        alignment = align_ocr(orig, corr)
        if not all(matches_match(alignment)):
            print('Failed: test_matches')
            print('Orig:', orig)
            print('Corr:', corr)
            print(alignment)
            print()
        self.assertEqual(all(matches_match(alignment)), True)

    # TODO Rewrite this to operate on AlignTokens
    @parameterized.parameterized.expand(testcases)
    def test_same_chars_categories(self, orig, corr):
        alignment = align_ocr(orig, corr)
        same_char_categorized = [tok for tok in alignment.aligned_tokens if tok.matchtype == 'same_chars']
        same_char_bools = [tok.orig.replace('_', '') == tok.corr for tok in same_char_categorized]
        self.assertEqual(all(same_char_bools), True)

    @parameterized.parameterized.expand(testcases)
    def test_same_char_matches(self, orig, corr):
        """Test whether tokens where orig and corr have the same chars (+ '_'), also have the same_chars category."""
        def has_samechars_category(algn):
            """Return list of booleans reflecting whether same-char matches actually have the same_chars category"""
            tokens = list(zip(algn.aligned_orig, [x.replace('_', '') for x in algn.aligned_orig], algn.correct, algn.matchtypes))
            bools = [bool(w == 'same_chars') for x, y, z, w in tokens if y and y == z and '_' in x and w != 'match']
            # If bools list is empty, just return a list with a True value.
            return bools if bools else [True]
        alignment = align_ocr(orig, corr)
        if not all(has_samechars_category(alignment)):
            print('Failed: test_same_char_matches')
            print('Orig:', orig)
            print('Corr:', corr)
            print(alignment)
            print()
        self.assertEqual(all(has_samechars_category(alignment)), True)

    @parameterized.parameterized.expand(testcases)
    def test_match_matches(self, orig, corr):
        """Test whether token alignments where orig == corr indeed have the 'match' category."""
        def has_match_category(algn):
            """Test whether a token alignment where orig == corr has the 'match' category."""
            tokens = list(zip(algn.aligned_orig, algn.correct, algn.matchtypes))
            bools = [bool(z == 'match') for x, y, z in tokens if x == y]
            # If bools list is empty, just return a list with a True value.
            return bools if bools else [True]
        alignment = align_ocr(orig, corr)
        if not all(has_match_category(alignment)):
            print('Failed: test_match_matches')
            print('Orig:', orig)
            print('Corr:', corr)
            print(alignment)
            print()
        self.assertEqual(all(has_match_category(alignment)), True)

    @parameterized.parameterized.expand(testcases)
    def test_lev_categories(self, orig, corr):
        """Test whether token alignments with levenshtein distance n have the correct category (lev_n)."""
        def lev_cat_matches(algn):
            """Test whether a token alignment with lev n has category lev_n"""
            def has_correct_lev(x, y, cat):
                lev = distance(x, y)
                return cat.endswith(str(lev))
            tokens = list(zip(algn.aligned_orig, algn.correct, algn.matchtypes))
            other_cats = ['match', 'same_chars']
            bools = [has_correct_lev(x, y, cat) for x, y, cat in tokens if '[-]' not in y and cat not in other_cats]
            # If bools list is empty, just return a list with a True value.
            return bools if bools else [True]
        alignment = align_ocr(orig, corr)
        if not all(lev_cat_matches(alignment)):
            print('Failed: test_lev_categories')
            print('Orig:', orig)
            print('Corr:', corr)
            print(alignment)
            print()
        self.assertEqual(all(lev_cat_matches(alignment)), True)

class getConfigsTest(unittest.TestCase):
    """Test the configuration option handling."""

    def test_get_testinput_path(self):
        pathresult = get_config_path('data', 'testinputdir')
        self.assertTrue(os.path.exists(pathresult))


class pdf2ImgTest(unittest.TestCase):
    def test_convert_from_path(self):
        """Make sure convert_from_path returns a list."""
        filepath = '/Users/phb514/my_seafile/Seafile/NorS MeMo Home/MeMo-Fraktur-OCR-cleaning/MeMo-Fraktur-OCR-data/testinput/1883_Brosboell_Krybskytten.pdf'
        with tempfile.TemporaryDirectory() as outpath:
            img_list = convert_from_path(filepath,
                                         thread_count=4,
                                         dpi=300,
                                         output_folder=outpath,
                                         fmt='jpeg')
        [img.close() for img in img_list]
        self.assertTrue(isinstance(img_list, list))
